CREATE TABLE IF NOT EXISTS merchant (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_no varchar(32) NOT NULL COMMENT '商户号',
    merchant_name varchar(128) NOT NULL COMMENT '商户名称',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    country_code varchar(8) NULL COMMENT '默认国家',
    currency varchar(8) NULL COMMENT '默认币种',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_merchant_no (merchant_no),
    KEY idx_tenant_status (tenant_id, status)
) COMMENT='支付商户';

CREATE TABLE IF NOT EXISTS merchant_app (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_id bigint NOT NULL COMMENT '商户ID',
    app_id varchar(64) NOT NULL COMMENT '应用ID',
    app_name varchar(128) NOT NULL COMMENT '应用名称',
    api_secret varchar(256) NOT NULL COMMENT 'API密钥',
    notify_url varchar(512) NULL COMMENT '默认通知地址',
    ip_whitelist varchar(1024) NULL COMMENT 'IP白名单',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_app_id (app_id),
    KEY idx_merchant_status (merchant_id, status),
    KEY idx_tenant_status (tenant_id, status)
) COMMENT='商户应用';

CREATE TABLE IF NOT EXISTS pay_method (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    method_code varchar(32) NOT NULL COMMENT '支付方式编码',
    method_name varchar(128) NOT NULL COMMENT '支付方式名称',
    country_code varchar(8) NOT NULL COMMENT '国家编码',
    currency varchar(8) NOT NULL COMMENT '币种',
    direction varchar(16) NOT NULL COMMENT 'PAYIN/PAYOUT/BOTH',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_method_scope (country_code, currency, method_code, direction)
) COMMENT='平台统一支付方式';

CREATE TABLE IF NOT EXISTS psp_provider (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    psp_code varchar(32) NOT NULL COMMENT 'PSP编码',
    psp_name varchar(128) NOT NULL COMMENT 'PSP名称',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    base_url varchar(512) NULL COMMENT '基础URL',
    config_json json NULL COMMENT '配置JSON',
    secret_json json NULL COMMENT '密钥JSON',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_psp_code (psp_code),
    KEY idx_status (status)
) COMMENT='PSP三方支付公司';

CREATE TABLE IF NOT EXISTS psp_method (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    psp_id bigint NOT NULL COMMENT 'PSP ID',
    method_code varchar(32) NOT NULL COMMENT '平台支付方式编码',
    psp_method_code varchar(64) NOT NULL COMMENT 'PSP支付方式编码',
    country_code varchar(8) NOT NULL COMMENT '国家编码',
    currency varchar(8) NOT NULL COMMENT '币种',
    direction varchar(16) NOT NULL COMMENT 'PAYIN/PAYOUT',
    min_amount decimal(20,6) NULL COMMENT '最小金额',
    max_amount decimal(20,6) NULL COMMENT '最大金额',
    daily_limit decimal(20,6) NULL COMMENT '日限额',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    config_json json NULL COMMENT '配置JSON',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_psp_method (psp_id, country_code, currency, method_code, direction),
    KEY idx_method_scope (country_code, currency, method_code, direction, status)
) COMMENT='PSP支付方式';

CREATE TABLE IF NOT EXISTS psp_route_rule (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NULL COMMENT '租户ID',
    merchant_id bigint NULL COMMENT '商户ID',
    app_id varchar(64) NULL COMMENT '应用ID',
    country_code varchar(8) NOT NULL COMMENT '国家编码',
    currency varchar(8) NOT NULL COMMENT '币种',
    method_code varchar(32) NOT NULL COMMENT '支付方式',
    direction varchar(16) NOT NULL COMMENT 'PAYIN/PAYOUT',
    psp_method_id bigint NOT NULL COMMENT 'PSP支付方式ID',
    priority int NOT NULL DEFAULT 100 COMMENT '优先级',
    weight int NOT NULL DEFAULT 100 COMMENT '权重',
    min_amount decimal(20,6) NULL COMMENT '最小金额',
    max_amount decimal(20,6) NULL COMMENT '最大金额',
    start_time time NULL COMMENT '开始时间',
    end_time time NULL COMMENT '结束时间',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_route_match (country_code, currency, method_code, direction, status, priority),
    KEY idx_merchant_match (tenant_id, merchant_id, app_id)
) COMMENT='PSP路由规则';

CREATE TABLE IF NOT EXISTS ledger_subject (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NULL COMMENT '租户ID',
    merchant_id bigint NULL COMMENT '商户ID',
    psp_id bigint NULL COMMENT 'PSP ID',
    subject_no varchar(64) NOT NULL COMMENT '资金主体编号',
    subject_type varchar(32) NOT NULL COMMENT 'MERCHANT/PSP/PLATFORM',
    subject_name varchar(128) NOT NULL COMMENT '资金主体名称',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_subject_no (subject_no),
    KEY idx_subject_scope (tenant_id, merchant_id, subject_type)
) COMMENT='资金主体';

CREATE TABLE IF NOT EXISTS ledger_account (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NULL COMMENT '租户ID',
    merchant_id bigint NULL COMMENT '商户ID',
    subject_id bigint NOT NULL COMMENT '资金主体ID',
    account_no varchar(64) NOT NULL COMMENT '账户编号',
    account_type varchar(32) NOT NULL COMMENT '账户类型',
    currency varchar(8) NOT NULL COMMENT '币种',
    balance decimal(20,6) NOT NULL DEFAULT 0 COMMENT '余额',
    debit_total decimal(20,6) NOT NULL DEFAULT 0 COMMENT '借方累计',
    credit_total decimal(20,6) NOT NULL DEFAULT 0 COMMENT '贷方累计',
    status tinyint NOT NULL DEFAULT 1 COMMENT '状态',
    version int NOT NULL DEFAULT 0 COMMENT '版本号',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_account_no (account_no),
    UNIQUE KEY uk_subject_type_currency (subject_id, account_type, currency),
    KEY idx_merchant_currency (merchant_id, currency),
    KEY idx_subject (subject_id)
) COMMENT='账务账户';

CREATE TABLE IF NOT EXISTS ledger_journal (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NULL COMMENT '租户ID',
    merchant_id bigint NULL COMMENT '商户ID',
    journal_no varchar(64) NOT NULL COMMENT '凭证号',
    biz_type varchar(32) NOT NULL COMMENT '业务类型',
    biz_no varchar(128) NOT NULL COMMENT '业务编号',
    currency varchar(8) NOT NULL COMMENT '币种',
    total_amount decimal(20,6) NOT NULL COMMENT '总金额',
    status varchar(32) NOT NULL COMMENT '状态',
    posted_at datetime(3) NULL COMMENT '过账时间',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_journal_no (journal_no),
    UNIQUE KEY uk_biz (biz_type, biz_no),
    KEY idx_merchant_created (merchant_id, created_at)
) COMMENT='记账凭证';

CREATE TABLE IF NOT EXISTS ledger_entry (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NULL COMMENT '租户ID',
    merchant_id bigint NULL COMMENT '商户ID',
    journal_id bigint NOT NULL COMMENT '凭证ID',
    journal_no varchar(64) NOT NULL COMMENT '凭证号',
    account_id bigint NOT NULL COMMENT '账户ID',
    account_no varchar(64) NOT NULL COMMENT '账户编号',
    direction varchar(16) NOT NULL COMMENT 'DEBIT/CREDIT',
    amount decimal(20,6) NOT NULL COMMENT '金额',
    balance_after decimal(20,6) NOT NULL COMMENT '发生后余额',
    summary varchar(256) NULL COMMENT '摘要',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_journal (journal_id),
    KEY idx_account_created (account_id, created_at),
    KEY idx_journal_no (journal_no)
) COMMENT='记账分录';
