-- Merchant order and notification schema for V1.
-- Covers payin orders, payout orders, merchant notification tasks, notification records, and order status history.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS pay_order (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_id bigint NOT NULL COMMENT '商户ID',
    merchant_no varchar(64) NOT NULL COMMENT '商户号快照',
    merchant_app_id bigint NOT NULL COMMENT '商户应用ID',
    app_id varchar(64) NOT NULL COMMENT '商户应用ID快照',
    pay_order_no varchar(128) NOT NULL COMMENT '平台代收订单号',
    merchant_order_no varchar(128) NOT NULL COMMENT '商户订单号',
    idempotency_key varchar(128) NOT NULL COMMENT '商户请求幂等键',
    request_id varchar(128) NULL DEFAULT NULL COMMENT '请求ID/链路请求号',
    order_source varchar(32) NOT NULL DEFAULT 'API' COMMENT '订单来源: API/ADMIN/SYSTEM',
    country_code varchar(8) NOT NULL COMMENT '国家编码',
    currency varchar(16) NOT NULL COMMENT '币种',
    method_code varchar(64) NOT NULL COMMENT '平台统一支付方式编码',
    amount decimal(24,8) NOT NULL COMMENT '订单金额',
    paid_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT '实际支付金额',
    merchant_fee_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT '商户手续费',
    psp_fee_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT 'PSP成本手续费',
    settle_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT '商户待结算金额',
    fee_rule_id bigint NULL DEFAULT NULL COMMENT '费用规则ID',
    fee_snapshot_json json NULL COMMENT '费用规则快照JSON',
    subject varchar(256) NULL DEFAULT NULL COMMENT '订单标题',
    description varchar(512) NULL DEFAULT NULL COMMENT '订单描述',
    client_ip varchar(64) NULL DEFAULT NULL COMMENT '商户侧用户IP',
    payer_json json NULL COMMENT '付款人扩展信息JSON，敏感信息需脱敏或加密',
    notify_url varchar(512) NULL DEFAULT NULL COMMENT '商户异步通知地址',
    return_url varchar(512) NULL DEFAULT NULL COMMENT '商户同步跳转地址',
    status varchar(32) NOT NULL DEFAULT 'CREATED' COMMENT '状态: CREATED/PROCESSING/SUCCESS/FAILED/CLOSED',
    status_reason varchar(512) NULL DEFAULT NULL COMMENT '当前状态原因',
    expire_at datetime(3) NULL DEFAULT NULL COMMENT '订单过期时间',
    paid_at datetime(3) NULL DEFAULT NULL COMMENT '支付成功时间',
    closed_at datetime(3) NULL DEFAULT NULL COMMENT '关闭时间',
    failed_at datetime(3) NULL DEFAULT NULL COMMENT '失败时间',
    route_rule_id bigint NULL DEFAULT NULL COMMENT '命中的PSP路由规则ID',
    route_snapshot_json json NULL COMMENT 'PSP路由快照JSON',
    psp_id bigint NULL DEFAULT NULL COMMENT 'PSP ID',
    psp_code varchar(64) NULL DEFAULT NULL COMMENT 'PSP编码快照',
    psp_method_id bigint NULL DEFAULT NULL COMMENT 'PSP支付方式ID',
    psp_method_code varchar(128) NULL DEFAULT NULL COMMENT 'PSP支付方式编码',
    psp_merchant_id bigint NULL DEFAULT NULL COMMENT 'PSP商户号配置ID',
    psp_merchant_no varchar(128) NULL DEFAULT NULL COMMENT 'PSP商户号快照',
    psp_request_no varchar(128) NULL DEFAULT NULL COMMENT '请求PSP的平台请求编号',
    psp_order_no varchar(128) NULL DEFAULT NULL COMMENT 'PSP订单号',
    psp_status varchar(64) NULL DEFAULT NULL COMMENT 'PSP状态',
    psp_raw_status varchar(128) NULL DEFAULT NULL COMMENT 'PSP原始状态',
    psp_pay_url varchar(1024) NULL DEFAULT NULL COMMENT 'PSP收银台/支付链接',
    psp_pay_params_json json NULL COMMENT 'PSP支付参数JSON',
    ledger_journal_no varchar(64) NULL DEFAULT NULL COMMENT '入账凭证号',
    settle_status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '结算状态: PENDING/RELEASED/HELD/CANCELLED',
    settle_at datetime(3) NULL DEFAULT NULL COMMENT '结算释放时间',
    settle_journal_no varchar(64) NULL DEFAULT NULL COMMENT '结算释放凭证号',
    outbox_event_id varchar(64) NULL DEFAULT NULL COMMENT '订单成功事件ID',
    extra_json json NULL COMMENT '订单扩展JSON',
    version int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_pay_order_no (tenant_id, pay_order_no),
    UNIQUE KEY uk_pay_merchant_order (tenant_id, merchant_id, merchant_order_no),
    UNIQUE KEY uk_pay_idempotency (tenant_id, merchant_id, idempotency_key),
    KEY idx_pay_order_status (tenant_id, status, created_at),
    KEY idx_pay_order_expire (tenant_id, status, expire_at),
    KEY idx_pay_order_settle (tenant_id, settle_status, paid_at),
    KEY idx_pay_order_merchant (tenant_id, merchant_id, created_at),
    KEY idx_pay_order_psp (psp_id, psp_order_no),
    KEY idx_pay_order_psp_request (tenant_id, psp_request_no),
    KEY idx_pay_order_method (tenant_id, country_code, currency, method_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代收订单';

CREATE TABLE IF NOT EXISTS payout_order (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_id bigint NOT NULL COMMENT '商户ID',
    merchant_no varchar(64) NOT NULL COMMENT '商户号快照',
    merchant_app_id bigint NOT NULL COMMENT '商户应用ID',
    app_id varchar(64) NOT NULL COMMENT '商户应用ID快照',
    payout_order_no varchar(128) NOT NULL COMMENT '平台代付订单号',
    merchant_order_no varchar(128) NOT NULL COMMENT '商户订单号',
    idempotency_key varchar(128) NOT NULL COMMENT '商户请求幂等键',
    request_id varchar(128) NULL DEFAULT NULL COMMENT '请求ID/链路请求号',
    order_source varchar(32) NOT NULL DEFAULT 'API' COMMENT '订单来源: API/ADMIN/SYSTEM',
    country_code varchar(8) NOT NULL COMMENT '国家编码',
    currency varchar(16) NOT NULL COMMENT '币种',
    method_code varchar(64) NOT NULL COMMENT '平台统一代付方式编码',
    amount decimal(24,8) NOT NULL COMMENT '代付金额',
    merchant_fee_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT '商户手续费',
    total_debit_amount decimal(24,8) NOT NULL COMMENT '商户扣减总额，通常为amount+fee',
    psp_fee_amount decimal(24,8) NOT NULL DEFAULT 0.00000000 COMMENT 'PSP成本手续费',
    fee_rule_id bigint NULL DEFAULT NULL COMMENT '费用规则ID',
    fee_snapshot_json json NULL COMMENT '费用规则快照JSON',
    beneficiary_name varchar(128) NULL DEFAULT NULL COMMENT '收款人姓名',
    beneficiary_account_cipher varchar(512) NULL DEFAULT NULL COMMENT '收款账号/钱包号密文',
    beneficiary_account_mask varchar(128) NULL DEFAULT NULL COMMENT '收款账号/钱包号掩码',
    beneficiary_account_hash varchar(128) NULL DEFAULT NULL COMMENT '收款账号/钱包号哈希',
    beneficiary_bank_code varchar(64) NULL DEFAULT NULL COMMENT '收款银行编码',
    beneficiary_wallet_type varchar(64) NULL DEFAULT NULL COMMENT '收款钱包类型',
    beneficiary_phone_cipher varchar(256) NULL DEFAULT NULL COMMENT '收款人手机号密文',
    beneficiary_phone_mask varchar(64) NULL DEFAULT NULL COMMENT '收款人手机号掩码',
    beneficiary_phone_hash varchar(128) NULL DEFAULT NULL COMMENT '收款人手机号哈希',
    beneficiary_email_cipher varchar(256) NULL DEFAULT NULL COMMENT '收款人邮箱密文',
    beneficiary_email_mask varchar(128) NULL DEFAULT NULL COMMENT '收款人邮箱掩码',
    beneficiary_email_hash varchar(128) NULL DEFAULT NULL COMMENT '收款人邮箱哈希',
    beneficiary_json json NULL COMMENT '收款人扩展JSON',
    purpose varchar(256) NULL DEFAULT NULL COMMENT '代付用途',
    notify_url varchar(512) NULL DEFAULT NULL COMMENT '商户异步通知地址',
    status varchar(32) NOT NULL DEFAULT 'CREATED' COMMENT '状态: CREATED/FROZEN/PROCESSING/SUCCESS/FAILED/CANCELLED',
    status_reason varchar(512) NULL DEFAULT NULL COMMENT '当前状态原因',
    submitted_at datetime(3) NULL DEFAULT NULL COMMENT '提交PSP时间',
    completed_at datetime(3) NULL DEFAULT NULL COMMENT '完成时间',
    failed_at datetime(3) NULL DEFAULT NULL COMMENT '失败时间',
    cancelled_at datetime(3) NULL DEFAULT NULL COMMENT '取消时间',
    fail_code varchar(128) NULL DEFAULT NULL COMMENT '失败码',
    fail_msg varchar(512) NULL DEFAULT NULL COMMENT '失败原因',
    hold_no varchar(64) NULL DEFAULT NULL COMMENT '冻结编号',
    freeze_journal_no varchar(64) NULL DEFAULT NULL COMMENT '冻结凭证号',
    success_journal_no varchar(64) NULL DEFAULT NULL COMMENT '成功扣款凭证号',
    release_journal_no varchar(64) NULL DEFAULT NULL COMMENT '失败解冻凭证号',
    route_rule_id bigint NULL DEFAULT NULL COMMENT '命中的PSP路由规则ID',
    route_snapshot_json json NULL COMMENT 'PSP路由快照JSON',
    psp_id bigint NULL DEFAULT NULL COMMENT 'PSP ID',
    psp_code varchar(64) NULL DEFAULT NULL COMMENT 'PSP编码快照',
    psp_method_id bigint NULL DEFAULT NULL COMMENT 'PSP支付方式ID',
    psp_method_code varchar(128) NULL DEFAULT NULL COMMENT 'PSP支付方式编码',
    psp_merchant_id bigint NULL DEFAULT NULL COMMENT 'PSP商户号配置ID',
    psp_merchant_no varchar(128) NULL DEFAULT NULL COMMENT 'PSP商户号快照',
    psp_request_no varchar(128) NULL DEFAULT NULL COMMENT '请求PSP的平台请求编号',
    psp_order_no varchar(128) NULL DEFAULT NULL COMMENT 'PSP订单号',
    psp_status varchar(64) NULL DEFAULT NULL COMMENT 'PSP状态',
    psp_raw_status varchar(128) NULL DEFAULT NULL COMMENT 'PSP原始状态',
    next_query_at datetime(3) NULL DEFAULT NULL COMMENT '下一次主动查询PSP状态时间',
    query_count int NOT NULL DEFAULT 0 COMMENT '主动查询次数',
    outbox_event_id varchar(64) NULL DEFAULT NULL COMMENT '订单终态事件ID',
    extra_json json NULL COMMENT '订单扩展JSON',
    version int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_payout_order_no (tenant_id, payout_order_no),
    UNIQUE KEY uk_payout_merchant_order (tenant_id, merchant_id, merchant_order_no),
    UNIQUE KEY uk_payout_idempotency (tenant_id, merchant_id, idempotency_key),
    KEY idx_payout_order_status (tenant_id, status, created_at),
    KEY idx_payout_order_query (tenant_id, status, next_query_at),
    KEY idx_payout_order_merchant (tenant_id, merchant_id, created_at),
    KEY idx_payout_order_psp (psp_id, psp_order_no),
    KEY idx_payout_order_psp_request (tenant_id, psp_request_no),
    KEY idx_payout_order_hold (tenant_id, hold_no),
    KEY idx_payout_beneficiary_account_hash (tenant_id, beneficiary_account_hash),
    KEY idx_payout_order_method (tenant_id, country_code, currency, method_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代付订单';

CREATE TABLE IF NOT EXISTS order_status_log (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_id bigint NULL DEFAULT NULL COMMENT '商户ID',
    log_no varchar(128) NOT NULL COMMENT '状态日志编号',
    order_type varchar(32) NOT NULL COMMENT '订单类型: PAY/PAYOUT',
    order_id bigint NOT NULL COMMENT '订单ID',
    order_no varchar(128) NOT NULL COMMENT '订单号',
    from_status varchar(32) NULL DEFAULT NULL COMMENT '变更前状态',
    to_status varchar(32) NOT NULL COMMENT '变更后状态',
    event_type varchar(64) NOT NULL COMMENT '触发事件',
    reason varchar(512) NULL DEFAULT NULL COMMENT '变更原因',
    operator_type varchar(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '操作方: SYSTEM/MERCHANT/PSP/ADMIN/SCHEDULER',
    operator_id varchar(128) NULL DEFAULT NULL COMMENT '操作方ID',
    request_id varchar(128) NULL DEFAULT NULL COMMENT '请求ID/链路请求号',
    trace_id varchar(128) NULL DEFAULT NULL COMMENT '链路追踪ID',
    metadata_json json NULL COMMENT '状态变更上下文JSON',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_status_log_no (tenant_id, log_no),
    KEY idx_order_status_order (tenant_id, order_type, order_no, created_at),
    KEY idx_order_status_event (tenant_id, event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单状态流转日志';

CREATE TABLE IF NOT EXISTS merchant_notify_task (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    merchant_id bigint NOT NULL COMMENT '商户ID',
    merchant_app_id bigint NOT NULL COMMENT '商户应用ID',
    app_id varchar(64) NOT NULL COMMENT '商户应用ID快照',
    task_no varchar(128) NOT NULL COMMENT '通知任务编号',
    biz_type varchar(64) NOT NULL COMMENT '业务类型: PAY_ORDER/PAYOUT_ORDER等',
    biz_id bigint NOT NULL COMMENT '业务ID',
    biz_no varchar(128) NOT NULL COMMENT '业务编号',
    event_type varchar(64) NOT NULL COMMENT '通知事件: PAY_SUCCESS/PAYOUT_FAILED等',
    source_event_id varchar(64) NULL DEFAULT NULL COMMENT '来源Outbox事件ID',
    notify_url varchar(512) NOT NULL COMMENT '通知地址',
    http_method varchar(16) NOT NULL DEFAULT 'POST' COMMENT 'HTTP方法',
    content_type varchar(64) NOT NULL DEFAULT 'application/json' COMMENT '请求Content-Type',
    charset varchar(32) NOT NULL DEFAULT 'UTF-8' COMMENT '请求字符集',
    sign_type varchar(32) NOT NULL DEFAULT 'HMAC_SHA256' COMMENT '签名方式',
    signature varchar(512) NULL DEFAULT NULL COMMENT '通知签名',
    payload_hash varchar(128) NOT NULL COMMENT '通知内容哈希',
    headers_json json NULL COMMENT '通知请求头JSON',
    payload_json json NOT NULL COMMENT '通知内容JSON',
    timeout_ms int NOT NULL DEFAULT 5000 COMMENT 'HTTP通知超时毫秒',
    status varchar(32) NOT NULL DEFAULT 'INIT' COMMENT '状态: INIT/PROCESSING/SUCCESS/FAILED/DEAD',
    retry_count int NOT NULL DEFAULT 0 COMMENT '已重试次数',
    max_retry_count int NOT NULL DEFAULT 16 COMMENT '最大重试次数',
    next_retry_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '下次重试时间',
    last_http_status int NULL DEFAULT NULL COMMENT '最后HTTP状态码',
    last_response_body text NULL COMMENT '最后响应体',
    last_error_msg varchar(1024) NULL DEFAULT NULL COMMENT '最后错误信息',
    last_attempt_at datetime(3) NULL DEFAULT NULL COMMENT '最后通知尝试时间',
    locked_by varchar(128) NULL DEFAULT NULL COMMENT '锁定节点',
    locked_at datetime(3) NULL DEFAULT NULL COMMENT '锁定时间',
    lock_until datetime(3) NULL DEFAULT NULL COMMENT '锁定过期时间',
    success_at datetime(3) NULL DEFAULT NULL COMMENT '通知成功时间',
    dead_at datetime(3) NULL DEFAULT NULL COMMENT '进入死信时间',
    trace_id varchar(128) NULL DEFAULT NULL COMMENT '链路追踪ID',
    remark varchar(512) NULL DEFAULT NULL COMMENT '备注',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_merchant_notify_task_no (tenant_id, task_no),
    UNIQUE KEY uk_merchant_notify_task_biz_event (tenant_id, biz_type, biz_no, event_type),
    KEY idx_merchant_notify_task_scan (tenant_id, status, next_retry_at, id),
    KEY idx_merchant_notify_task_biz (tenant_id, biz_type, biz_no),
    KEY idx_merchant_notify_task_merchant (tenant_id, merchant_id, created_at),
    KEY idx_merchant_notify_task_lock (lock_until, locked_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商户通知任务';

CREATE TABLE IF NOT EXISTS merchant_notify_record (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id bigint NOT NULL COMMENT '租户ID',
    notify_task_id bigint NOT NULL COMMENT '通知任务ID',
    task_no varchar(128) NOT NULL COMMENT '通知任务编号',
    attempt_no int NOT NULL COMMENT '第几次通知',
    notify_url varchar(512) NOT NULL COMMENT '通知地址',
    http_method varchar(16) NOT NULL DEFAULT 'POST' COMMENT 'HTTP方法',
    content_type varchar(64) NOT NULL DEFAULT 'application/json' COMMENT '请求Content-Type',
    request_signature varchar(512) NULL DEFAULT NULL COMMENT '请求签名',
    request_headers_json json NULL COMMENT '请求头JSON',
    request_body text NULL COMMENT '请求体',
    response_headers_json json NULL COMMENT '响应头JSON',
    response_status int NULL DEFAULT NULL COMMENT 'HTTP响应状态码',
    response_body text NULL COMMENT '响应体',
    success tinyint NOT NULL DEFAULT 0 COMMENT '是否成功: 0否 1是',
    error_msg varchar(1024) NULL DEFAULT NULL COMMENT '错误信息',
    cost_ms bigint NULL DEFAULT NULL COMMENT '耗时毫秒',
    started_at datetime(3) NULL DEFAULT NULL COMMENT '开始通知时间',
    finished_at datetime(3) NULL DEFAULT NULL COMMENT '完成通知时间',
    trace_id varchar(128) NULL DEFAULT NULL COMMENT '链路追踪ID',
    created_by bigint NULL DEFAULT NULL COMMENT '创建人ID',
    created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by bigint NULL DEFAULT NULL COMMENT '更新人ID',
    updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_merchant_notify_record_attempt (notify_task_id, attempt_no),
    KEY idx_merchant_notify_record_task (tenant_id, task_no),
    KEY idx_merchant_notify_record_success (tenant_id, success, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商户通知记录';
