-- Philippines demo seed data for V1 merchant foundation.
-- Tenant id: 1990654400050675713.
-- Demo secrets are placeholders. Do not use them in production.

SET NAMES utf8mb4;

INSERT INTO sys_tenant (
    id,
    name,
    code,
    status,
    domain,
    currency,
    timezone,
    lang,
    remark,
    created_by,
    created_at,
    updated_by,
    updated_at
) VALUES (
    1990654400050675713,
    'Philippines Demo Tenant',
    'PH_DEMO',
    1,
    'ph-demo.gk-union.local',
    'PHP',
    'Asia/Manila',
    'en-US',
    'Philippines V1 demo tenant',
    1,
    CURRENT_TIMESTAMP(3),
    1,
    CURRENT_TIMESTAMP(3)
);

INSERT INTO merchant (
    id,
    tenant_id,
    merchant_no,
    merchant_name,
    merchant_short_name,
    merchant_type,
    status,
    risk_status,
    country_code,
    default_currency,
    timezone,
    lang,
    contact_name,
    contact_email,
    contact_phone,
    business_license_no,
    settle_mode,
    settle_cycle,
    min_settle_amount,
    config_json,
    remark,
    created_by,
    created_at,
    updated_by,
    updated_at
) VALUES
(
    1990654500050675701,
    1990654400050675713,
    'M_PH_MANILA_001',
    'Manila Demo Trading Inc.',
    'Manila Demo',
    'COMPANY',
    1,
    'NORMAL',
    'PH',
    'PHP',
    'Asia/Manila',
    'en-US',
    'Maria Santos',
    'ops.manila.demo@example.com',
    '+639171000001',
    'PH-SEC-2026-0001',
    'AUTO',
    'T1',
    1000.00000000,
    JSON_OBJECT('businessScene', 'ECOMMERCE', 'settleHoldDays', 1),
    'Philippines Manila demo merchant',
    1,
    CURRENT_TIMESTAMP(3),
    1,
    CURRENT_TIMESTAMP(3)
),
(
    1990654500050675702,
    1990654400050675713,
    'M_PH_CEBU_001',
    'Cebu Demo Services Corp.',
    'Cebu Demo',
    'COMPANY',
    1,
    'NORMAL',
    'PH',
    'PHP',
    'Asia/Manila',
    'en-US',
    'Juan Dela Cruz',
    'ops.cebu.demo@example.com',
    '+639171000002',
    'PH-SEC-2026-0002',
    'MANUAL',
    'T1',
    500.00000000,
    JSON_OBJECT('businessScene', 'SERVICES', 'settleHoldDays', 1),
    'Philippines Cebu demo merchant',
    1,
    CURRENT_TIMESTAMP(3),
    1,
    CURRENT_TIMESTAMP(3)
);

INSERT INTO merchant_app (
    id,
    tenant_id,
    merchant_id,
    app_id,
    app_name,
    app_type,
    status,
    sign_type,
    encrypt_type,
    api_secret,
    secret_version,
    secret_updated_at,
    merchant_public_key,
    platform_public_key,
    notify_url,
    return_url,
    ip_whitelist_json,
    allowed_currency_json,
    allowed_method_json,
    rate_limit_qps,
    nonce_ttl_seconds,
    config_json,
    remark,
    created_by,
    created_at,
    updated_by,
    updated_at
) VALUES
(
    1990654600050675701,
    1990654400050675713,
    1990654500050675701,
    'APP_PH_MANILA_001',
    'Manila Demo API App',
    'API',
    1,
    'HMAC_SHA256',
    'NONE',
    'dev_secret_ph_manila_001_change_me',
    1,
    CURRENT_TIMESTAMP(3),
    NULL,
    NULL,
    'https://merchant-manila.example.com/api/payments/notify',
    'https://merchant-manila.example.com/payments/return',
    JSON_ARRAY('127.0.0.1', '203.0.113.10'),
    JSON_ARRAY('PHP'),
    JSON_ARRAY('GCASH', 'MAYA', 'BANK_TRANSFER'),
    50,
    300,
    JSON_OBJECT('payinEnabled', true, 'payoutEnabled', true),
    'Demo app for Manila merchant',
    1,
    CURRENT_TIMESTAMP(3),
    1,
    CURRENT_TIMESTAMP(3)
),
(
    1990654600050675702,
    1990654400050675713,
    1990654500050675702,
    'APP_PH_CEBU_001',
    'Cebu Demo API App',
    'API',
    1,
    'HMAC_SHA256',
    'NONE',
    'dev_secret_ph_cebu_001_change_me',
    1,
    CURRENT_TIMESTAMP(3),
    NULL,
    NULL,
    'https://merchant-cebu.example.com/api/payments/notify',
    'https://merchant-cebu.example.com/payments/return',
    JSON_ARRAY('127.0.0.1', '203.0.113.20'),
    JSON_ARRAY('PHP'),
    JSON_ARRAY('GCASH', 'MAYA'),
    30,
    300,
    JSON_OBJECT('payinEnabled', true, 'payoutEnabled', false),
    'Demo app for Cebu merchant',
    1,
    CURRENT_TIMESTAMP(3),
    1,
    CURRENT_TIMESTAMP(3)
);
