/*
 Navicat Premium Dump SQL

 Source Server         : 涓汉鏁版嵁搴?HK)
 Source Server Type    : MySQL
 Source Server Version : 80036 (8.0.36)
 Source Host           : rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306
 Source Schema         : gk-union

 Target Server Type    : MySQL
 Target Server Version : 80036 (8.0.36)
 File Encoding         : 65001

 Date: 10/06/2026 12:31:23
*/


-- ----------------------------
-- Table structure for merchant
-- ----------------------------
DROP TABLE IF EXISTS "merchant";
CREATE TABLE "merchant"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_no" varchar(64) NOT NULL,
  "merchant_name" varchar(128) NOT NULL,
  "merchant_short_name" varchar(64) NULL DEFAULT NULL,
  "merchant_type" varchar(32) NOT NULL DEFAULT 'COMPANY',
  "status" SMALLINT NOT NULL DEFAULT 1,
  "risk_status" varchar(32) NOT NULL DEFAULT 'NORMAL',
  "country_code" varchar(8) NOT NULL,
  "default_currency" varchar(16) NOT NULL,
  "timezone" varchar(64) NOT NULL DEFAULT 'UTC',
  "lang" varchar(16) NOT NULL DEFAULT 'zh-CN',
  "contact_name" varchar(64) NULL DEFAULT NULL,
  "contact_email" varchar(128) NULL DEFAULT NULL,
  "contact_phone" varchar(32) NULL DEFAULT NULL,
  "tg_user_id" bigint NULL DEFAULT NULL,
  "business_license_no" varchar(128) NULL DEFAULT NULL,
  "settle_mode" varchar(32) NOT NULL DEFAULT 'MANUAL',
  "settle_cycle" varchar(32) NOT NULL DEFAULT 'T1',
  "min_settle_amount" decimal(24, 8) NULL DEFAULT NULL,
  "config_json" json NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_merchant_no" ON "merchant" ("merchant_no" ASC);
CREATE UNIQUE INDEX "uk_merchant_tenant_name" ON "merchant" ("tenant_id" ASC, "merchant_name" ASC);
CREATE INDEX "idx_merchant_tenant_status" ON "merchant" ("tenant_id" ASC, "status" ASC);
CREATE INDEX "idx_merchant_country_currency" ON "merchant" ("tenant_id" ASC, "country_code" ASC, "default_currency" ASC);
CREATE INDEX "idx_merchant_risk_status" ON "merchant" ("tenant_id" ASC, "risk_status" ASC);

-- ----------------------------
-- Table structure for merchant_app
-- ----------------------------
DROP TABLE IF EXISTS "merchant_app";
CREATE TABLE "merchant_app"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "app_id" varchar(64) NOT NULL,
  "app_name" varchar(128) NOT NULL,
  "app_type" varchar(32) NOT NULL DEFAULT 'API',
  "app_env" varchar(16) NOT NULL DEFAULT 'PROD',
  "status" SMALLINT NOT NULL DEFAULT 1,
  "sign_type" varchar(32) NOT NULL DEFAULT 'HMAC_SHA256',
  "encrypt_type" varchar(32) NOT NULL DEFAULT 'NONE',
  "api_secret" varchar(512) NULL DEFAULT NULL,
  "secret_version" int NOT NULL DEFAULT 1,
  "secret_updated_at" TIMESTAMP NULL DEFAULT NULL,
  "notify_url" varchar(512) NULL DEFAULT NULL,
  "return_url" varchar(512) NULL DEFAULT NULL,
  "rate_limit_qps" int NOT NULL DEFAULT 50,
  "nonce_ttl_seconds" int NOT NULL DEFAULT 300,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_merchant_app_id" ON "merchant_app" ("app_id" ASC);
CREATE INDEX "idx_merchant_app_merchant_status" ON "merchant_app" ("tenant_id" ASC, "merchant_id" ASC, "status" ASC);
CREATE INDEX "idx_merchant_app_env" ON "merchant_app" ("tenant_id" ASC, "merchant_id" ASC, "app_env" ASC);
CREATE INDEX "idx_merchant_app_tenant_status" ON "merchant_app" ("tenant_id" ASC, "status" ASC);

-- ----------------------------
-- Table structure for merchant_fee_rule
-- ----------------------------
DROP TABLE IF EXISTS "merchant_fee_rule";
CREATE TABLE "merchant_fee_rule"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "merchant_app_id" bigint NULL DEFAULT NULL,
  "rule_name" varchar(128) NOT NULL,
  "direction" varchar(32) NOT NULL,
  "country_code" varchar(16) NULL DEFAULT NULL,
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NULL DEFAULT NULL,
  "min_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "max_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "fee_mode" varchar(32) NOT NULL,
  "fee_rate" decimal(18, 8) NOT NULL DEFAULT 0.00000000,
  "fee_fixed" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "min_fee" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "max_fee" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "fee_bearer" varchar(32) NOT NULL DEFAULT 'MERCHANT',
  "settle_mode" varchar(32) NOT NULL DEFAULT 'DEDUCT',
  "priority" int NOT NULL DEFAULT 100,
  "effective_at" TIMESTAMP NULL DEFAULT NULL,
  "expire_at" TIMESTAMP NULL DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE INDEX "idx_fee_rule_merchant" ON "merchant_fee_rule" ("tenant_id" ASC, "merchant_id" ASC, "direction" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_fee_rule_app" ON "merchant_fee_rule" ("tenant_id" ASC, "merchant_app_id" ASC, "direction" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_fee_rule_match" ON "merchant_fee_rule" ("tenant_id" ASC, "merchant_id" ASC, "direction" ASC, "country_code" ASC, "currency" ASC, "method_code" ASC, "status" ASC, "priority" ASC);
CREATE INDEX "idx_fee_rule_order_match" ON "merchant_fee_rule" ("tenant_id" ASC, "merchant_id" ASC, "merchant_app_id" ASC, "direction" ASC, "currency" ASC, "method_code" ASC, "status" ASC, "priority" ASC, "id" ASC);
CREATE INDEX "idx_fee_rule_effective" ON "merchant_fee_rule" ("tenant_id" ASC, "status" ASC, "effective_at" ASC, "expire_at" ASC);

-- ----------------------------
-- Table structure for merchant_notify_record
-- ----------------------------
DROP TABLE IF EXISTS "merchant_notify_record";
CREATE TABLE "merchant_notify_record"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "notify_task_id" bigint NOT NULL,
  "task_no" varchar(128) NOT NULL,
  "attempt_no" int NOT NULL,
  "notify_url" varchar(512) NOT NULL,
  "http_method" varchar(16) NOT NULL DEFAULT 'POST',
  "content_type" varchar(64) NOT NULL DEFAULT 'application/json',
  "request_signature" varchar(512) NULL DEFAULT NULL,
  "request_headers_json" json NULL,
  "request_body" text NULL,
  "response_headers_json" json NULL,
  "response_status" int NULL DEFAULT NULL,
  "response_body" text NULL,
  "success" SMALLINT NOT NULL DEFAULT 0,
  "error_msg" varchar(1024) NULL DEFAULT NULL,
  "cost_ms" bigint NULL DEFAULT NULL,
  "started_at" TIMESTAMP NULL DEFAULT NULL,
  "finished_at" TIMESTAMP NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_merchant_notify_record_attempt" ON "merchant_notify_record" ("notify_task_id" ASC, "attempt_no" ASC);
CREATE INDEX "idx_merchant_notify_record_task" ON "merchant_notify_record" ("tenant_id" ASC, "task_no" ASC);
CREATE INDEX "idx_merchant_notify_record_success" ON "merchant_notify_record" ("tenant_id" ASC, "success" ASC, "created_at" ASC);

-- ----------------------------
-- Table structure for merchant_notify_task
-- ----------------------------
DROP TABLE IF EXISTS "merchant_notify_task";
CREATE TABLE "merchant_notify_task"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "merchant_app_id" bigint NOT NULL,
  "app_id" varchar(64) NOT NULL,
  "task_no" varchar(128) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NOT NULL,
  "biz_no" varchar(128) NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "source_event_id" varchar(64) NULL DEFAULT NULL,
  "notify_url" varchar(512) NOT NULL,
  "http_method" varchar(16) NOT NULL DEFAULT 'POST',
  "content_type" varchar(64) NOT NULL DEFAULT 'application/json',
  "charset" varchar(32) NOT NULL DEFAULT 'UTF-8',
  "sign_type" varchar(32) NOT NULL DEFAULT 'HMAC_SHA256',
  "signature" varchar(512) NULL DEFAULT NULL,
  "payload_hash" varchar(128) NOT NULL,
  "headers_json" json NULL,
  "payload_json" json NOT NULL,
  "timeout_ms" int NOT NULL DEFAULT 5000,
  "status" varchar(32) NOT NULL DEFAULT 'INIT',
  "retry_count" int NOT NULL DEFAULT 0,
  "max_retry_count" int NOT NULL DEFAULT 16,
  "next_retry_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "last_http_status" int NULL DEFAULT NULL,
  "last_response_body" text NULL,
  "last_error_msg" varchar(1024) NULL DEFAULT NULL,
  "last_attempt_at" TIMESTAMP NULL DEFAULT NULL,
  "locked_by" varchar(128) NULL DEFAULT NULL,
  "locked_at" TIMESTAMP NULL DEFAULT NULL,
  "lock_until" TIMESTAMP NULL DEFAULT NULL,
  "success_at" TIMESTAMP NULL DEFAULT NULL,
  "dead_at" TIMESTAMP NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_merchant_notify_task_no" ON "merchant_notify_task" ("tenant_id" ASC, "task_no" ASC);
CREATE UNIQUE INDEX "uk_merchant_notify_task_biz_event" ON "merchant_notify_task" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC, "event_type" ASC);
CREATE INDEX "idx_merchant_notify_task_scan" ON "merchant_notify_task" ("tenant_id" ASC, "status" ASC, "next_retry_at" ASC, "id" ASC);
CREATE INDEX "idx_merchant_notify_task_biz" ON "merchant_notify_task" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC);
CREATE INDEX "idx_merchant_notify_task_merchant" ON "merchant_notify_task" ("tenant_id" ASC, "merchant_id" ASC, "created_at" ASC);
CREATE INDEX "idx_merchant_notify_task_lock" ON "merchant_notify_task" ("lock_until" ASC, "locked_by" ASC);

-- ----------------------------
-- Table structure for merchant_request_log
-- ----------------------------
DROP TABLE IF EXISTS "merchant_request_log";
CREATE TABLE "merchant_request_log"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NULL DEFAULT NULL,
  "merchant_id" bigint NULL DEFAULT NULL,
  "merchant_no" varchar(64) NULL DEFAULT NULL,
  "merchant_app_id" bigint NULL DEFAULT NULL,
  "app_id" varchar(64) NULL DEFAULT NULL,
  "request_no" varchar(128) NOT NULL,
  "api_path" varchar(256) NOT NULL,
  "api_name" varchar(128) NULL DEFAULT NULL,
  "http_method" varchar(16) NOT NULL DEFAULT 'POST',
  "client_ip" varchar(64) NULL DEFAULT NULL,
  "user_agent" varchar(512) NULL DEFAULT NULL,
  "request_body_hash" varchar(128) NULL DEFAULT NULL,
  "request_body_json" json NULL,
  "request_params_json" json NULL,
  "sign_type" varchar(32) NULL DEFAULT NULL,
  "sign_value" varchar(256) NULL DEFAULT NULL,
  "sign_valid" SMALLINT NULL DEFAULT NULL,
  "timestamp_value" varchar(64) NULL DEFAULT NULL,
  "nonce_value" varchar(128) NULL DEFAULT NULL,
  "biz_type" varchar(64) NULL DEFAULT NULL,
  "biz_no" varchar(128) NULL DEFAULT NULL,
  "merchant_order_no" varchar(128) NULL DEFAULT NULL,
  "response_code" varchar(64) NULL DEFAULT NULL,
  "response_message" varchar(512) NULL DEFAULT NULL,
  "response_body_json" json NULL,
  "status" varchar(32) NOT NULL DEFAULT 'RECEIVED',
  "error_code" varchar(64) NULL DEFAULT NULL,
  "error_message" varchar(512) NULL DEFAULT NULL,
  "cost_ms" bigint NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_merchant_request_no" ON "merchant_request_log" ("request_no" ASC);
CREATE INDEX "idx_merchant_request_app" ON "merchant_request_log" ("tenant_id" ASC, "merchant_app_id" ASC, "created_at" ASC);
CREATE INDEX "idx_merchant_request_merchant" ON "merchant_request_log" ("tenant_id" ASC, "merchant_id" ASC, "created_at" ASC);
CREATE INDEX "idx_merchant_request_api" ON "merchant_request_log" ("api_path" ASC, "created_at" ASC);
CREATE INDEX "idx_merchant_request_biz" ON "merchant_request_log" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC);
CREATE INDEX "idx_merchant_request_order" ON "merchant_request_log" ("tenant_id" ASC, "merchant_id" ASC, "merchant_order_no" ASC);
CREATE INDEX "idx_merchant_request_status" ON "merchant_request_log" ("status" ASC, "created_at" ASC);
CREATE INDEX "idx_merchant_request_trace" ON "merchant_request_log" ("trace_id" ASC);

