-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS merchant CASCADE;
CREATE TABLE merchant (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_no varchar(64) NOT NULL,
  merchant_name varchar(128) NOT NULL,
  merchant_short_name varchar(64) NULL,
  merchant_type varchar(32) NOT NULL DEFAULT 'COMPANY',
  status smallint NOT NULL DEFAULT 1,
  risk_status varchar(32) NOT NULL DEFAULT 'NORMAL',
  country_code varchar(8) NOT NULL,
  default_currency varchar(16) NOT NULL,
  timezone varchar(64) NOT NULL DEFAULT 'UTC',
  lang varchar(16) NOT NULL DEFAULT 'zh-CN',
  contact_name varchar(64) NULL,
  contact_email varchar(128) NULL,
  contact_phone varchar(32) NULL,
  tg_user_id bigint NULL,
  business_license_no varchar(128) NULL,
  settle_mode varchar(32) NOT NULL DEFAULT 'MANUAL',
  settle_cycle varchar(32) NOT NULL DEFAULT 'T1',
  min_settle_amount numeric(24, 8) NULL,
  config_json json NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_uk_merchant_no ON merchant (merchant_no);
CREATE UNIQUE INDEX uk_merchant_uk_merchant_tenant_name ON merchant (tenant_id, merchant_name);
CREATE INDEX idx_merchant_idx_merchant_tenant_status ON merchant (tenant_id, status);
CREATE INDEX idx_merchant_idx_merchant_country_currency ON merchant (tenant_id, country_code, default_currency);
CREATE INDEX idx_merchant_idx_merchant_risk_status ON merchant (tenant_id, risk_status);

DROP TABLE IF EXISTS merchant_api_ip_whitelist CASCADE;
CREATE TABLE merchant_api_ip_whitelist (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  rule_name varchar(128) NULL,
  ip_pattern varchar(128) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_api_ip_whitelist PRIMARY KEY (id),
  CONSTRAINT chk_merchant_api_ip_whitelist_1 CHECK (status in (1,2,3))
);
CREATE INDEX idx_merchant_api_ip_whitelist_idx_merchant_api_ip_scope ON merchant_api_ip_whitelist (tenant_id, merchant_id, status);
CREATE INDEX idx_merchant_api_ip_whitelist_idx_merchant_api_ip_status ON merchant_api_ip_whitelist (status, created_at);
CREATE INDEX idx_merchant_api_ip_whitelist_idx_merchant_api_ip_pattern ON merchant_api_ip_whitelist (tenant_id, merchant_id, status, ip_pattern);

DROP TABLE IF EXISTS merchant_app CASCADE;
CREATE TABLE merchant_app (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  app_id varchar(64) NOT NULL,
  app_name varchar(128) NOT NULL,
  app_type varchar(32) NOT NULL DEFAULT 'API',
  app_env varchar(16) NOT NULL DEFAULT 'PROD',
  status smallint NOT NULL DEFAULT 1,
  sign_type varchar(32) NOT NULL DEFAULT 'HMAC_SHA256',
  encrypt_type varchar(32) NOT NULL DEFAULT 'NONE',
  api_secret varchar(512) NULL,
  secret_version integer NOT NULL DEFAULT 1,
  secret_updated_at timestamp(3) NULL,
  notify_url varchar(512) NULL,
  return_url varchar(512) NULL,
  rate_limit_qps integer NOT NULL DEFAULT 50,
  nonce_ttl_seconds integer NOT NULL DEFAULT 300,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_app PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_app_uk_merchant_app_id ON merchant_app (app_id);
CREATE INDEX idx_merchant_app_idx_merchant_app_merchant_status ON merchant_app (tenant_id, merchant_id, status);
CREATE INDEX idx_merchant_app_idx_merchant_app_tenant_status ON merchant_app (tenant_id, status);
CREATE INDEX idx_merchant_app_idx_merchant_app_env ON merchant_app (tenant_id, merchant_id, app_env);

DROP TABLE IF EXISTS merchant_fee_rule CASCADE;
CREATE TABLE merchant_fee_rule (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_app_id bigint NULL,
  rule_name varchar(128) NOT NULL,
  direction varchar(32) NOT NULL,
  country_code varchar(16) NULL,
  currency varchar(16) NOT NULL,
  method_code varchar(64) NULL,
  min_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  fee_mode varchar(32) NOT NULL,
  fee_rate numeric(18, 8) NOT NULL DEFAULT 0.00000000,
  fee_fixed numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  min_fee numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_fee numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  fee_bearer varchar(32) NOT NULL DEFAULT 'MERCHANT',
  settle_mode varchar(32) NOT NULL DEFAULT 'DEDUCT',
  priority integer NOT NULL DEFAULT 100,
  effective_at timestamp(3) NULL,
  expire_at timestamp(3) NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_fee_rule PRIMARY KEY (id)
);
CREATE INDEX idx_merchant_fee_rule_idx_fee_rule_merchant ON merchant_fee_rule (tenant_id, merchant_id, direction, currency, status);
CREATE INDEX idx_merchant_fee_rule_idx_fee_rule_app ON merchant_fee_rule (tenant_id, merchant_app_id, direction, currency, status);
CREATE INDEX idx_merchant_fee_rule_idx_fee_rule_match ON merchant_fee_rule (tenant_id, merchant_id, direction, country_code, currency, method_code, status, priority);
CREATE INDEX idx_merchant_fee_rule_idx_fee_rule_effective ON merchant_fee_rule (tenant_id, status, effective_at, expire_at);
CREATE INDEX idx_merchant_fee_rule_idx_fee_rule_order_match ON merchant_fee_rule (tenant_id, merchant_id, merchant_app_id, direction, currency, method_code, status, priority, id);

DROP TABLE IF EXISTS merchant_notify_record CASCADE;
CREATE TABLE merchant_notify_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  notify_task_id bigint NOT NULL,
  task_no varchar(128) NOT NULL,
  attempt_no integer NOT NULL,
  notify_url varchar(512) NOT NULL,
  http_method varchar(16) NOT NULL DEFAULT 'POST',
  content_type varchar(64) NOT NULL DEFAULT 'application/json',
  request_signature varchar(512) NULL,
  request_headers_json json NULL,
  request_body text NULL,
  response_headers_json json NULL,
  response_status integer NULL,
  response_body text NULL,
  success smallint NOT NULL DEFAULT 0,
  error_msg varchar(1024) NULL,
  cost_ms bigint NULL,
  started_at timestamp(3) NULL,
  finished_at timestamp(3) NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_notify_record PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_notify_record_uk_merchant_notify_record_attempt ON merchant_notify_record (notify_task_id, attempt_no);
CREATE INDEX idx_merchant_notify_record_idx_merchant_notify_record_task ON merchant_notify_record (tenant_id, task_no);
CREATE INDEX idx_merchant_notify_record_idx_merchant_notify_reco_a6dc6399 ON merchant_notify_record (tenant_id, success, created_at);

DROP TABLE IF EXISTS merchant_notify_task CASCADE;
CREATE TABLE merchant_notify_task (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_app_id bigint NOT NULL,
  app_id varchar(64) NOT NULL,
  task_no varchar(128) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NOT NULL,
  biz_no varchar(128) NOT NULL,
  event_type varchar(64) NOT NULL,
  source_event_id varchar(64) NULL,
  notify_url varchar(512) NOT NULL,
  http_method varchar(16) NOT NULL DEFAULT 'POST',
  content_type varchar(64) NOT NULL DEFAULT 'application/json',
  charset varchar(32) NOT NULL DEFAULT 'UTF-8',
  sign_type varchar(32) NOT NULL DEFAULT 'HMAC_SHA256',
  signature varchar(512) NULL,
  payload_hash varchar(128) NOT NULL,
  headers_json json NULL,
  payload_json json NOT NULL,
  timeout_ms integer NOT NULL DEFAULT 5000,
  status varchar(32) NOT NULL DEFAULT 'INIT',
  retry_count integer NOT NULL DEFAULT 0,
  max_retry_count integer NOT NULL DEFAULT 16,
  next_retry_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_http_status integer NULL,
  last_response_body text NULL,
  last_error_msg varchar(1024) NULL,
  last_attempt_at timestamp(3) NULL,
  locked_by varchar(128) NULL,
  locked_at timestamp(3) NULL,
  lock_until timestamp(3) NULL,
  success_at timestamp(3) NULL,
  dead_at timestamp(3) NULL,
  trace_id varchar(128) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_notify_task PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_notify_task_uk_merchant_notify_task_no ON merchant_notify_task (tenant_id, task_no);
CREATE UNIQUE INDEX uk_merchant_notify_task_uk_merchant_notify_task_biz_event ON merchant_notify_task (tenant_id, biz_type, biz_no, event_type);
CREATE INDEX idx_merchant_notify_task_idx_merchant_notify_task_scan ON merchant_notify_task (tenant_id, status, next_retry_at, id);
CREATE INDEX idx_merchant_notify_task_idx_merchant_notify_task_biz ON merchant_notify_task (tenant_id, biz_type, biz_no);
CREATE INDEX idx_merchant_notify_task_idx_merchant_notify_task_merchant ON merchant_notify_task (tenant_id, merchant_id, created_at);
CREATE INDEX idx_merchant_notify_task_idx_merchant_notify_task_lock ON merchant_notify_task (lock_until, locked_by);

DROP TABLE IF EXISTS merchant_request_log CASCADE;
CREATE TABLE merchant_request_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NULL,
  merchant_id bigint NULL,
  merchant_no varchar(64) NULL,
  merchant_app_id bigint NULL,
  app_id varchar(64) NULL,
  request_no varchar(128) NOT NULL,
  api_path varchar(256) NOT NULL,
  api_name varchar(128) NULL,
  http_method varchar(16) NOT NULL DEFAULT 'POST',
  client_ip varchar(64) NULL,
  user_agent varchar(512) NULL,
  request_body_hash varchar(128) NULL,
  request_body_json json NULL,
  request_params_json json NULL,
  sign_type varchar(32) NULL,
  sign_value varchar(256) NULL,
  sign_valid smallint NULL,
  timestamp_value varchar(64) NULL,
  nonce_value varchar(128) NULL,
  biz_type varchar(64) NULL,
  biz_no varchar(128) NULL,
  merchant_order_no varchar(128) NULL,
  response_code varchar(64) NULL,
  response_message varchar(512) NULL,
  response_body_json json NULL,
  status varchar(32) NOT NULL DEFAULT 'RECEIVED',
  error_code varchar(64) NULL,
  error_message varchar(512) NULL,
  cost_ms bigint NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_request_log PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_request_log_uk_merchant_request_no ON merchant_request_log (request_no);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_app ON merchant_request_log (tenant_id, merchant_app_id, created_at);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_merchant ON merchant_request_log (tenant_id, merchant_id, created_at);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_api ON merchant_request_log (api_path, created_at);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_biz ON merchant_request_log (tenant_id, biz_type, biz_no);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_order ON merchant_request_log (tenant_id, merchant_id, merchant_order_no);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_status ON merchant_request_log (status, created_at);
CREATE INDEX idx_merchant_request_log_idx_merchant_request_trace ON merchant_request_log (trace_id);
