
DROP TABLE IF EXISTS "sys_api_ip_whitelist";
DROP TABLE IF EXISTS "merchant_api_ip_whitelist";
CREATE TABLE "merchant_api_ip_whitelist" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "rule_name" varchar(128) NULL,
  "ip_pattern" varchar(128) NOT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL,
  "created_by" bigint NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
  CONSTRAINT "chk_merchant_api_ip_status" CHECK ("status" in (1,2,3))
);
CREATE INDEX "idx_merchant_api_ip_scope" ON "merchant_api_ip_whitelist" ("tenant_id", "merchant_id", "status");
CREATE INDEX "idx_merchant_api_ip_status" ON "merchant_api_ip_whitelist" ("status", "created_at");

