package com.gk.payment.dto;

import lombok.Data;

import java.math.BigDecimal;
import java.time.Instant;

@Data
public class PayoutOrderDTO {
    private Long id;
    private Long tenantId;
    private Long merchantId;
    private String merchantNo;
    private Long merchantAppId;
    private String appId;
    private String payoutOrderNo;
    private String merchantOrderNo;
    private String idempotencyKey;
    private String requestId;
    private String orderSource;
    private String countryCode;
    private String currency;
    private String methodCode;
    private BigDecimal amount;
    private BigDecimal merchantFeeAmount;
    private BigDecimal totalDebitAmount;
    private BigDecimal pspFeeAmount;
    private Long feeRuleId;
    private String feeSnapshotJson;
    private String beneficiaryName;
    private String beneficiaryAccountCipher;
    private String beneficiaryAccountMask;
    private String beneficiaryAccountHash;
    private String beneficiaryBankCode;
    private String beneficiaryWalletType;
    private String beneficiaryPhoneCipher;
    private String beneficiaryPhoneMask;
    private String beneficiaryPhoneHash;
    private String beneficiaryEmailCipher;
    private String beneficiaryEmailMask;
    private String beneficiaryEmailHash;
    private String beneficiaryJson;
    private String purpose;
    private String notifyUrl;
    private String status;
    private String statusReason;
    private Instant submittedAt;
    private Instant completedAt;
    private Instant failedAt;
    private Instant cancelledAt;
    private String failCode;
    private String failMsg;
    private String holdNo;
    private String freezeJournalNo;
    private String successJournalNo;
    private String releaseJournalNo;
    private Long routeRuleId;
    private String routeSnapshotJson;
    private Long pspId;
    private String pspCode;
    private Long pspMethodId;
    private String pspMethodCode;
    private Long pspMerchantId;
    private String pspMerchantNo;
    private String pspRequestNo;
    private String pspOrderNo;
    private String pspStatus;
    private String pspRawStatus;
    private Instant nextQueryAt;
    private Integer queryCount;
    private String outboxEventId;
    private String extraJson;
    private Integer version;
    private String remark;
    private Long createdBy;
    private Instant createdAt;
    private Long updatedBy;
    private Instant updatedAt;
}
