-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS mq_consume_record CASCADE;
CREATE TABLE mq_consume_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  event_id varchar(64) NOT NULL,
  topic varchar(128) NOT NULL,
  tag varchar(128) NOT NULL,
  message_key varchar(256) NOT NULL,
  consumer_group varchar(128) NOT NULL,
  consumer_name varchar(128) NULL,
  consume_status varchar(32) NOT NULL DEFAULT 'PROCESSING',
  retry_count integer NOT NULL DEFAULT 0,
  first_consumed_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_consumed_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  success_at timestamp(3) NULL,
  last_error_code varchar(64) NULL,
  last_error_msg varchar(1024) NULL,
  rocketmq_msg_id varchar(128) NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_mq_consume_record PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_mq_consume_record_uk_mq_consume_event_group ON mq_consume_record (event_id, consumer_group);
CREATE INDEX idx_mq_consume_record_idx_mq_consume_message_group ON mq_consume_record (message_key, consumer_group);
CREATE INDEX idx_mq_consume_record_idx_mq_consume_status ON mq_consume_record (consume_status, last_consumed_at);
CREATE INDEX idx_mq_consume_record_idx_mq_consume_topic_tag ON mq_consume_record (topic, tag, consumer_group);

DROP TABLE IF EXISTS mq_outbox CASCADE;
CREATE TABLE mq_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  event_id varchar(64) NOT NULL,
  event_type varchar(64) NOT NULL,
  event_version integer NOT NULL DEFAULT 1,
  source_service varchar(64) NOT NULL,
  aggregate_type varchar(64) NOT NULL,
  aggregate_id bigint NULL,
  aggregate_no varchar(128) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  topic varchar(128) NOT NULL,
  tag varchar(128) NOT NULL,
  message_key varchar(256) NOT NULL,
  sharding_key varchar(128) NULL,
  producer_group varchar(128) NULL,
  delay_level integer NULL,
  deliver_at timestamp(3) NULL,
  headers_json json NULL,
  payload_json json NOT NULL,
  publish_status varchar(32) NOT NULL DEFAULT 'INIT',
  consume_status varchar(32) NOT NULL DEFAULT 'INIT',
  retry_count integer NOT NULL DEFAULT 0,
  max_retry_count integer NOT NULL DEFAULT 16,
  next_retry_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  locked_by varchar(128) NULL,
  locked_at timestamp(3) NULL,
  lock_until timestamp(3) NULL,
  rocketmq_msg_id varchar(128) NULL,
  sent_at timestamp(3) NULL,
  consumed_at timestamp(3) NULL,
  dead_at timestamp(3) NULL,
  last_error_code varchar(64) NULL,
  last_error_msg varchar(1024) NULL,
  trace_id varchar(128) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_mq_outbox PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_mq_outbox_uk_mq_outbox_event ON mq_outbox (event_id);
CREATE UNIQUE INDEX uk_mq_outbox_uk_mq_outbox_biz_event ON mq_outbox (tenant_id, biz_type, biz_no, event_type);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_publish_scan ON mq_outbox (publish_status, next_retry_at, id);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_consume_scan ON mq_outbox (consume_status, next_retry_at, id);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_lock ON mq_outbox (lock_until, locked_by);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_topic_tag ON mq_outbox (topic, tag, created_at);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_aggregate ON mq_outbox (tenant_id, aggregate_type, aggregate_no);
CREATE INDEX idx_mq_outbox_idx_mq_outbox_message_key ON mq_outbox (message_key);

DROP TABLE IF EXISTS sys_login_ip_whitelist CASCADE;
CREATE TABLE sys_login_ip_whitelist (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subject_type varchar(32) NOT NULL,
  tenant_id bigint NULL,
  merchant_id bigint NULL,
  subject_id bigint NULL,
  rule_name varchar(128) NULL,
  ip_pattern varchar(128) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_sys_login_ip_whitelist PRIMARY KEY (id),
  CONSTRAINT chk_sys_login_ip_whitelist_1 CHECK (status in (1,2,3)),
  CONSTRAINT chk_sys_login_ip_whitelist_2 CHECK (subject_type in ('PLATFORM','TENANT','MERCHANT'))
);
CREATE INDEX idx_sys_login_ip_whitelist_idx_login_ip_subject ON sys_login_ip_whitelist (subject_type, tenant_id, merchant_id, subject_id, status);
CREATE INDEX idx_sys_login_ip_whitelist_idx_login_ip_status ON sys_login_ip_whitelist (status, created_at);
