
DROP TABLE IF EXISTS "sys_login_ip_whitelist";
CREATE TABLE "sys_login_ip_whitelist" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "subject_type" varchar(32) NOT NULL,
  "tenant_id" bigint NULL DEFAULT NULL,
  "merchant_id" bigint NULL DEFAULT NULL,
  "subject_id" bigint NULL DEFAULT NULL,
  "rule_name" varchar(128) NULL DEFAULT NULL,
  "ip_pattern" varchar(128) NOT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
  CONSTRAINT "chk_login_ip_subject_type" CHECK ("subject_type" in ('PLATFORM','TENANT','MERCHANT')),
  CONSTRAINT "chk_login_ip_status" CHECK ("status" in (1,2,3))
);
CREATE INDEX "idx_login_ip_subject" ON "sys_login_ip_whitelist" ("subject_type", "tenant_id", "merchant_id", "subject_id", "status");
CREATE INDEX "idx_login_ip_status" ON "sys_login_ip_whitelist" ("status", "created_at");

