-- Database outbox schema.
-- V1 can be consumed by Quartz inside the monolith.
-- Later versions can publish the same rows to RocketMQ without changing business tables.


CREATE TABLE IF NOT EXISTS mq_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id bigint NOT NULL,
    event_id varchar(64) NOT NULL,
    event_type varchar(64) NOT NULL,
    event_version int NOT NULL DEFAULT 1,
    source_service varchar(64) NOT NULL,

    aggregate_type varchar(64) NOT NULL,
    aggregate_id bigint NULL DEFAULT NULL,
    aggregate_no varchar(128) NOT NULL,
    biz_type varchar(64) NOT NULL,
    biz_id bigint NULL DEFAULT NULL,
    biz_no varchar(128) NOT NULL,

    topic varchar(128) NOT NULL,
    tag varchar(128) NOT NULL,
    message_key varchar(256) NOT NULL,
    sharding_key varchar(128) NULL DEFAULT NULL,
    producer_group varchar(128) NULL DEFAULT NULL,
    delay_level int NULL DEFAULT NULL,
    deliver_at TIMESTAMP NULL DEFAULT NULL,

    headers_json json NULL,
    payload_json json NOT NULL,

    publish_status varchar(32) NOT NULL DEFAULT 'INIT',
    consume_status varchar(32) NOT NULL DEFAULT 'INIT',
    retry_count int NOT NULL DEFAULT 0,
    max_retry_count int NOT NULL DEFAULT 16,
    next_retry_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    locked_by varchar(128) NULL DEFAULT NULL,
    locked_at TIMESTAMP NULL DEFAULT NULL,
    lock_until TIMESTAMP NULL DEFAULT NULL,

    rocketmq_msg_id varchar(128) NULL DEFAULT NULL,
    sent_at TIMESTAMP NULL DEFAULT NULL,
    consumed_at TIMESTAMP NULL DEFAULT NULL,
    dead_at TIMESTAMP NULL DEFAULT NULL,
    last_error_code varchar(64) NULL DEFAULT NULL,
    last_error_msg varchar(1024) NULL DEFAULT NULL,

    trace_id varchar(128) NULL DEFAULT NULL,
    remark varchar(512) NULL DEFAULT NULL,
    created_by bigint NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by bigint NULL DEFAULT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
) DEFAULT CHARSET=utf8mb4

CREATE TABLE IF NOT EXISTS mq_consume_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id bigint NOT NULL,
    event_id varchar(64) NOT NULL,
    topic varchar(128) NOT NULL,
    tag varchar(128) NOT NULL,
    message_key varchar(256) NOT NULL,
    consumer_group varchar(128) NOT NULL,
    consumer_name varchar(128) NULL DEFAULT NULL,
    consume_status varchar(32) NOT NULL DEFAULT 'PROCESSING',
    retry_count int NOT NULL DEFAULT 0,
    first_consumed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    last_consumed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    success_at TIMESTAMP NULL DEFAULT NULL,
    last_error_code varchar(64) NULL DEFAULT NULL,
    last_error_msg varchar(1024) NULL DEFAULT NULL,
    rocketmq_msg_id varchar(128) NULL DEFAULT NULL,
    trace_id varchar(128) NULL DEFAULT NULL,
    created_by bigint NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by bigint NULL DEFAULT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
) DEFAULT CHARSET=utf8mb4
