/*
 Navicat Premium Dump SQL

 Source Server         : 涓汉鏁版嵁搴?HK)
 Source Server Type    : MySQL
 Source Server Version : 80036 (8.0.36)
 Source Host           : rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306
 Source Schema         : gk-union

 Target Server Type    : MySQL
 Target Server Version : 80036 (8.0.36)
 File Encoding         : 65001

 Date: 10/06/2026 12:31:23
*/


-- ----------------------------
-- Table structure for psp_account
-- ----------------------------
DROP TABLE IF EXISTS "psp_account";
CREATE TABLE "psp_account"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "psp_id" bigint NOT NULL,
  "psp_account_no" varchar(128) NOT NULL,
  "psp_account_name" varchar(128) NULL DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "secret_type" varchar(32) NOT NULL DEFAULT 'HMAC',
  "api_key" varchar(256) NULL DEFAULT NULL,
  "api_secret" varchar(512) NULL DEFAULT NULL,
  "callback_secret" varchar(512) NULL DEFAULT NULL,
  "config_json" json NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_psp_account_no" ON "psp_account" ("psp_account_no" ASC);
CREATE INDEX "idx_psp_account_tenant" ON "psp_account" ("tenant_id" ASC, "psp_id" ASC, "status" ASC);
CREATE INDEX "idx_psp_account_no" ON "psp_account" ("psp_id" ASC, "psp_account_no" ASC);

-- ----------------------------
-- Table structure for psp_callback_log
-- ----------------------------
DROP TABLE IF EXISTS "psp_callback_log";
CREATE TABLE "psp_callback_log"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NULL DEFAULT NULL,
  "psp_id" bigint NOT NULL,
  "psp_code" varchar(64) NOT NULL,
  "biz_type" varchar(64) NULL DEFAULT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NULL DEFAULT NULL,
  "psp_order_no" varchar(128) NULL DEFAULT NULL,
  "callback_type" varchar(64) NOT NULL,
  "callback_id" varchar(128) NULL DEFAULT NULL,
  "callback_key" varchar(256) NOT NULL,
  "body_hash" varchar(128) NOT NULL,
  "headers_json" json NULL,
  "body_json" json NULL,
  "raw_body" text NULL,
  "signature" varchar(512) NULL DEFAULT NULL,
  "verify_status" varchar(32) NOT NULL DEFAULT 'INIT',
  "process_status" varchar(32) NOT NULL DEFAULT 'INIT',
  "error_msg" varchar(1024) NULL DEFAULT NULL,
  "received_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "processed_at" TIMESTAMP NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_psp_callback_key" ON "psp_callback_log" ("psp_id" ASC, "callback_key" ASC);
CREATE INDEX "idx_psp_callback_biz" ON "psp_callback_log" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC);
CREATE INDEX "idx_psp_callback_order" ON "psp_callback_log" ("psp_id" ASC, "psp_order_no" ASC);
CREATE INDEX "idx_psp_callback_process" ON "psp_callback_log" ("process_status" ASC, "received_at" ASC);

-- ----------------------------
-- Table structure for psp_fee_rule
-- ----------------------------
DROP TABLE IF EXISTS "psp_fee_rule";
CREATE TABLE "psp_fee_rule"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "psp_id" bigint NOT NULL,
  "psp_account_id" bigint NULL DEFAULT NULL,
  "psp_method_id" bigint NULL DEFAULT NULL,
  "psp_method_code" varchar(64) NULL DEFAULT NULL,
  "rule_name" varchar(128) NOT NULL,
  "direction" varchar(16) NOT NULL,
  "country_code" varchar(8) NULL DEFAULT NULL,
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NULL DEFAULT NULL,
  "min_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "max_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "fee_mode" varchar(32) NOT NULL,
  "fee_rate" decimal(18, 8) NOT NULL DEFAULT 0.00000000,
  "fee_fixed" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "min_fee" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "max_fee" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "priority" int NOT NULL DEFAULT 100,
  "effective_at" TIMESTAMP NULL DEFAULT NULL,
  "expire_at" TIMESTAMP NULL DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE INDEX "idx_psp_fee_rule_psp" ON "psp_fee_rule" ("tenant_id" ASC, "psp_id" ASC, "direction" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_psp_fee_rule_account" ON "psp_fee_rule" ("tenant_id" ASC, "psp_account_id" ASC, "direction" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_psp_fee_rule_method" ON "psp_fee_rule" ("tenant_id" ASC, "psp_method_id" ASC, "direction" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_psp_fee_rule_match" ON "psp_fee_rule" ("tenant_id" ASC, "psp_id" ASC, "psp_account_id" ASC, "psp_method_id" ASC, "country_code" ASC, "currency" ASC, "method_code" ASC, "direction" ASC, "status" ASC, "priority" ASC);
CREATE INDEX "idx_psp_fee_rule_effective" ON "psp_fee_rule" ("tenant_id" ASC, "status" ASC, "effective_at" ASC, "expire_at" ASC);

-- ----------------------------
-- Table structure for psp_method
-- ----------------------------
DROP TABLE IF EXISTS "psp_method";
CREATE TABLE "psp_method"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "psp_id" bigint NOT NULL,
  "psp_code" varchar(64) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "psp_method_code" varchar(128) NOT NULL,
  "method_name" varchar(128) NULL DEFAULT NULL,
  "country_code" varchar(8) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "direction" varchar(16) NOT NULL,
  "min_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "max_amount" decimal(24, 8) NOT NULL DEFAULT '0.00000000',
  "daily_limit" decimal(24, 8) NULL DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "config_json" json NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_psp_method_scope" ON "psp_method" ("psp_id" ASC, "country_code" ASC, "currency" ASC, "method_code" ASC, "direction" ASC);
CREATE INDEX "idx_psp_method_match" ON "psp_method" ("country_code" ASC, "currency" ASC, "method_code" ASC, "direction" ASC, "status" ASC);
CREATE INDEX "idx_psp_method_psp" ON "psp_method" ("psp_id" ASC, "status" ASC);

-- ----------------------------
-- Table structure for psp_provider
-- ----------------------------
DROP TABLE IF EXISTS "psp_provider";
CREATE TABLE "psp_provider"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "psp_code" varchar(64) NOT NULL,
  "psp_name" varchar(128) NOT NULL,
  "country_code" varchar(8) NULL DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "base_url" varchar(512) NULL DEFAULT NULL,
  "api_version" varchar(32) NULL DEFAULT NULL,
  "support_payin" SMALLINT NOT NULL DEFAULT 1,
  "support_payout" SMALLINT NOT NULL DEFAULT 1,
  "config_json" json NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_psp_provider_tenant_code" ON "psp_provider" ("tenant_id" ASC, "psp_code" ASC);
CREATE INDEX "idx_psp_provider_country_status" ON "psp_provider" ("tenant_id" ASC, "country_code" ASC, "status" ASC);
CREATE INDEX "idx_psp_provider_status" ON "psp_provider" ("tenant_id" ASC, "status" ASC);

-- ----------------------------
-- Table structure for psp_request_log
-- ----------------------------
DROP TABLE IF EXISTS "psp_request_log";
CREATE TABLE "psp_request_log"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NULL DEFAULT NULL,
  "psp_id" bigint NOT NULL,
  "psp_code" varchar(64) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NOT NULL,
  "request_no" varchar(128) NOT NULL,
  "psp_request_no" varchar(128) NULL DEFAULT NULL,
  "psp_order_no" varchar(128) NULL DEFAULT NULL,
  "request_url" varchar(1024) NULL DEFAULT NULL,
  "http_method" varchar(16) NULL DEFAULT NULL,
  "request_headers_json" json NULL,
  "request_body" text NULL,
  "response_status" int NULL DEFAULT NULL,
  "response_body" text NULL,
  "success" SMALLINT NULL DEFAULT NULL,
  "error_code" varchar(128) NULL DEFAULT NULL,
  "error_msg" varchar(1024) NULL DEFAULT NULL,
  "cost_ms" bigint NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_psp_request_no" ON "psp_request_log" ("request_no" ASC);
CREATE INDEX "idx_psp_request_biz" ON "psp_request_log" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC);
CREATE INDEX "idx_psp_request_psp_order" ON "psp_request_log" ("psp_id" ASC, "psp_order_no" ASC);
CREATE INDEX "idx_psp_request_created" ON "psp_request_log" ("tenant_id" ASC, "created_at" ASC);
