-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS psp_account CASCADE;
CREATE TABLE psp_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  psp_id bigint NOT NULL,
  psp_account_no varchar(128) NOT NULL,
  psp_account_name varchar(128) NULL,
  status smallint NOT NULL DEFAULT 1,
  secret_type varchar(32) NOT NULL DEFAULT 'HMAC',
  api_key varchar(256) NULL,
  api_secret varchar(512) NULL,
  callback_secret varchar(512) NULL,
  config_json json NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_account PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_account_uk_psp_account_no ON psp_account (psp_account_no);
CREATE INDEX idx_psp_account_idx_psp_account_tenant ON psp_account (tenant_id, psp_id, status);
CREATE INDEX idx_psp_account_idx_psp_account_no ON psp_account (psp_id, psp_account_no);

DROP TABLE IF EXISTS psp_bank_mapping CASCADE;
CREATE TABLE psp_bank_mapping (
  id bigint NOT NULL,
  psp_id bigint NOT NULL,
  country_code varchar(8) NOT NULL,
  currency varchar(8) NOT NULL,
  bank_code varchar(64) NOT NULL,
  psp_bank_code varchar(128) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  sort integer NOT NULL DEFAULT 100,
  remark varchar(500) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_bank_mapping PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_bank_mapping_uk_psp_country_currency_bank ON psp_bank_mapping (psp_id, country_code, currency, bank_code);
CREATE INDEX idx_psp_bank_mapping_idx_psp_bank_code ON psp_bank_mapping (psp_id, psp_bank_code);
CREATE INDEX idx_psp_bank_mapping_idx_bank ON psp_bank_mapping (bank_code, country_code, currency);

DROP TABLE IF EXISTS psp_callback_ip_whitelist CASCADE;
CREATE TABLE psp_callback_ip_whitelist (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  psp_code varchar(64) NOT NULL,
  rule_name varchar(128) NULL,
  ip_pattern varchar(128) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_callback_ip_whitelist PRIMARY KEY (id),
  CONSTRAINT chk_psp_callback_ip_whitelist_1 CHECK (status in (1,2,3))
);
CREATE INDEX idx_psp_callback_ip_whitelist_idx_psp_callback_ip_scope ON psp_callback_ip_whitelist (psp_code, status);
CREATE INDEX idx_psp_callback_ip_whitelist_idx_psp_callback_ip_status ON psp_callback_ip_whitelist (status, created_at);

DROP TABLE IF EXISTS psp_callback_log CASCADE;
CREATE TABLE psp_callback_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NULL,
  psp_id bigint NOT NULL,
  psp_code varchar(64) NOT NULL,
  biz_type varchar(64) NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NULL,
  psp_order_no varchar(128) NULL,
  callback_type varchar(64) NOT NULL,
  callback_id varchar(128) NULL,
  callback_key varchar(256) NOT NULL,
  body_hash varchar(128) NOT NULL,
  headers_json json NULL,
  body_json json NULL,
  raw_body text NULL,
  signature varchar(512) NULL,
  verify_status varchar(32) NOT NULL DEFAULT 'INIT',
  process_status varchar(32) NOT NULL DEFAULT 'INIT',
  error_msg varchar(1024) NULL,
  received_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at timestamp(3) NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_callback_log PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_callback_log_uk_psp_callback_key ON psp_callback_log (psp_id, callback_key);
CREATE INDEX idx_psp_callback_log_idx_psp_callback_biz ON psp_callback_log (tenant_id, biz_type, biz_no);
CREATE INDEX idx_psp_callback_log_idx_psp_callback_order ON psp_callback_log (psp_id, psp_order_no);
CREATE INDEX idx_psp_callback_log_idx_psp_callback_process ON psp_callback_log (process_status, received_at);

DROP TABLE IF EXISTS psp_fee_rule CASCADE;
CREATE TABLE psp_fee_rule (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  psp_id bigint NOT NULL,
  psp_account_id bigint NULL,
  psp_method_id bigint NULL,
  method_code varchar(64) NOT NULL,
  psp_method_code varchar(64) NOT NULL,
  rule_name varchar(128) NOT NULL,
  direction varchar(16) NOT NULL,
  country_code varchar(8) NULL,
  currency varchar(16) NOT NULL,
  min_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  fee_mode varchar(32) NOT NULL,
  fee_rate numeric(18, 8) NOT NULL DEFAULT 0.00000000,
  fee_fixed numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  min_fee numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_fee numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  priority integer NOT NULL DEFAULT 100,
  effective_at timestamp(3) NULL,
  expire_at timestamp(3) NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_fee_rule PRIMARY KEY (id)
);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_psp ON psp_fee_rule (tenant_id, psp_id, direction, currency, status);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_account ON psp_fee_rule (tenant_id, psp_account_id, direction, currency, status);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_method ON psp_fee_rule (tenant_id, psp_method_id, direction, currency, status);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_match ON psp_fee_rule (tenant_id, psp_id, psp_account_id, psp_method_id, country_code, currency, method_code, direction, status, priority);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_effective ON psp_fee_rule (tenant_id, status, effective_at, expire_at);
CREATE INDEX idx_psp_fee_rule_idx_psp_fee_rule_plan_match ON psp_fee_rule (tenant_id, psp_id, psp_account_id, psp_method_id, currency, method_code, direction, status, priority, id);

DROP TABLE IF EXISTS psp_method CASCADE;
CREATE TABLE psp_method (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  psp_id bigint NOT NULL,
  psp_code varchar(64) NOT NULL,
  method_code varchar(64) NOT NULL,
  psp_method_code varchar(128) NOT NULL,
  method_name varchar(128) NULL,
  country_code varchar(8) NOT NULL,
  currency varchar(16) NOT NULL,
  direction varchar(16) NOT NULL,
  min_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  daily_limit numeric(24, 8) NULL,
  status smallint NOT NULL DEFAULT 1,
  config_json json NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_method PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_method_uk_psp_method_scope ON psp_method (psp_id, country_code, currency, method_code, direction);
CREATE INDEX idx_psp_method_idx_psp_method_match ON psp_method (country_code, currency, method_code, direction, status);
CREATE INDEX idx_psp_method_idx_psp_method_psp ON psp_method (psp_id, status);

DROP TABLE IF EXISTS psp_provider CASCADE;
CREATE TABLE psp_provider (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  psp_code varchar(64) NOT NULL,
  psp_name varchar(128) NOT NULL,
  country_code varchar(8) NULL,
  status smallint NOT NULL DEFAULT 1,
  base_url varchar(512) NULL,
  api_version varchar(32) NULL,
  support_payin smallint NOT NULL DEFAULT 1,
  support_payout smallint NOT NULL DEFAULT 1,
  config_json json NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_provider PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_provider_uk_psp_provider_tenant_code ON psp_provider (tenant_id, psp_code);
CREATE INDEX idx_psp_provider_idx_psp_provider_country_status ON psp_provider (tenant_id, country_code, status);
CREATE INDEX idx_psp_provider_idx_psp_provider_status ON psp_provider (tenant_id, status);

DROP TABLE IF EXISTS psp_request_log CASCADE;
CREATE TABLE psp_request_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NULL,
  psp_id bigint NOT NULL,
  psp_code varchar(64) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  request_no varchar(128) NOT NULL,
  psp_request_no varchar(128) NULL,
  psp_order_no varchar(128) NULL,
  request_url varchar(1024) NULL,
  http_method varchar(16) NULL,
  request_headers_json json NULL,
  request_body text NULL,
  response_status integer NULL,
  response_body text NULL,
  success smallint NULL,
  error_code varchar(128) NULL,
  error_msg varchar(1024) NULL,
  cost_ms bigint NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_psp_request_log PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_psp_request_log_uk_psp_request_no ON psp_request_log (request_no);
CREATE INDEX idx_psp_request_log_idx_psp_request_biz ON psp_request_log (tenant_id, biz_type, biz_no);
CREATE INDEX idx_psp_request_log_idx_psp_request_psp_order ON psp_request_log (psp_id, psp_order_no);
CREATE INDEX idx_psp_request_log_idx_psp_request_created ON psp_request_log (tenant_id, created_at);
