
DROP TABLE IF EXISTS "psp_callback_ip_whitelist";
CREATE TABLE "psp_callback_ip_whitelist" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "psp_code" varchar(64) NOT NULL,
  "rule_name" varchar(128) NULL,
  "ip_pattern" varchar(128) NOT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL,
  "created_by" bigint NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
  CONSTRAINT "chk_psp_callback_ip_status" CHECK ("status" in (1,2,3))
);
CREATE INDEX "idx_psp_callback_ip_scope" ON "psp_callback_ip_whitelist" ("psp_code", "status");
CREATE INDEX "idx_psp_callback_ip_status" ON "psp_callback_ip_whitelist" ("status", "created_at");

