CREATE TABLE `payment_plan_catalog` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `merchant_id` bigint NOT NULL COMMENT '商户ID',
  `merchant_app_id` bigint NOT NULL DEFAULT 0 COMMENT '商户应用ID; 不区分应用时为0',
  `direction` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '交易方向: PAYIN/PAYOUT',
  `country_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '国家编码; 无国家维度时为空字符串',
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '币种',
  `method_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付/出款方式编码',
  `version` bigint NOT NULL COMMENT '配置版本号',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态: STAGING/ACTIVE/RETIRED',
  `bucket_count` int NOT NULL DEFAULT 0 COMMENT '金额决策桶数量',
  `route_option_count` int NOT NULL DEFAULT 0 COMMENT '路由候选数量',
  `config_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '参与编译配置的哈希值',
  `compiled_at` datetime(3) NOT NULL COMMENT '编译时间',
  `activated_at` datetime(3) DEFAULT NULL COMMENT '激活时间',
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_plan_catalog_version` (`tenant_id`, `merchant_id`, `merchant_app_id`, `direction`, `country_code`, `currency`, `method_code`, `version`),
  KEY `idx_payment_plan_catalog_active` (`tenant_id`, `merchant_id`, `merchant_app_id`, `direction`, `country_code`, `currency`, `method_code`, `status`),
  KEY `idx_payment_plan_catalog_created` (`tenant_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付决策表头';

CREATE TABLE `payment_plan_bucket` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `catalog_id` bigint NOT NULL COMMENT '支付决策表ID',
  `bucket_start_amount` decimal(24,8) NOT NULL COMMENT '金额区间开始，包含',
  `bucket_end_amount` decimal(24,8) DEFAULT NULL COMMENT '金额区间结束，不包含; NULL表示无上限',
  `merchant_fee_rule_id` bigint NOT NULL COMMENT '商户费率规则ID',
  `merchant_fee_snapshot_json` json DEFAULT NULL COMMENT '商户费率规则快照',
  `sort` int NOT NULL DEFAULT 0 COMMENT '桶排序',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_payment_plan_bucket_catalog` (`tenant_id`, `catalog_id`, `sort`),
  KEY `idx_payment_plan_bucket_amount` (`tenant_id`, `catalog_id`, `bucket_start_amount`, `bucket_end_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付决策金额桶';

CREATE TABLE `payment_plan_route_option` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `catalog_id` bigint NOT NULL COMMENT '支付决策表ID',
  `bucket_id` bigint NOT NULL COMMENT '金额桶ID',
  `route_rule_id` bigint NOT NULL COMMENT 'PSP路由规则ID',
  `psp_id` bigint NOT NULL COMMENT 'PSP Provider ID',
  `psp_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PSP编码快照',
  `psp_method_id` bigint NOT NULL COMMENT 'PSP支付/出款方式ID',
  `psp_method_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PSP支付/出款方式编码快照',
  `psp_account_id` bigint NOT NULL COMMENT 'PSP账户ID',
  `psp_account_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PSP账户编号快照',
  `psp_fee_rule_id` bigint DEFAULT NULL COMMENT 'PSP成本费率规则ID',
  `psp_fee_snapshot_json` json DEFAULT NULL COMMENT 'PSP成本费率规则快照',
  `priority` int NOT NULL DEFAULT 100 COMMENT '优先级，数字越小越优先',
  `weight` int NOT NULL DEFAULT 100 COMMENT '同优先级下权重',
  `fallback_order` int NOT NULL DEFAULT 100 COMMENT '失败后的备用顺序',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/DISABLED',
  `sort` int NOT NULL DEFAULT 0 COMMENT '展示排序',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_payment_plan_route_bucket` (`tenant_id`, `bucket_id`, `status`, `priority`, `fallback_order`),
  KEY `idx_payment_plan_route_catalog` (`tenant_id`, `catalog_id`, `bucket_id`, `sort`),
  KEY `idx_payment_plan_route_psp` (`tenant_id`, `psp_id`, `psp_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付决策PSP候选路由';
