SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `merchant_wallet_statement` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `statement_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商户钱包流水号',
  `merchant_id` bigint NOT NULL COMMENT '商户ID',
  `merchant_no` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商户编号快照',
  `merchant_app_id` bigint DEFAULT NULL COMMENT '商户应用ID快照',
  `journal_id` bigint NOT NULL COMMENT '账务凭证ID',
  `journal_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账务凭证号',
  `entry_id` bigint NOT NULL COMMENT '关联账务分录ID',
  `biz_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务类型',
  `biz_id` bigint DEFAULT NULL COMMENT '业务ID',
  `biz_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '系统业务单号',
  `merchant_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商户订单号快照',
  `event_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账务事件',
  `account_id` bigint NOT NULL COMMENT '商户账户ID',
  `account_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商户账户号',
  `account_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商户账户类型',
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '币种',
  `effect_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水效果: IN/OUT/FREEZE/UNFREEZE/ADJUST',
  `biz_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '业务金额/订单本金',
  `fee_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '商户手续费',
  `net_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '商户净额/本次业务影响金额',
  `balance_change` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '余额变化金额',
  `balance_before` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '变动前余额',
  `balance_after` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '变动后余额',
  `source_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ORDER' COMMENT '来源: ORDER/SETTLE/RECON/MANUAL/SYSTEM',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'POSTED' COMMENT '状态: POSTED/REVERSED',
  `posted_at` datetime(3) NOT NULL COMMENT '入账时间',
  `trace_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '链路追踪ID',
  `summary` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商户侧摘要',
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_wallet_statement_no` (`tenant_id`,`statement_no`),
  UNIQUE KEY `uk_merchant_wallet_statement_entry` (`tenant_id`,`entry_id`),
  KEY `idx_merchant_wallet_statement_merchant_posted` (`tenant_id`,`merchant_id`,`posted_at`),
  KEY `idx_merchant_wallet_statement_order` (`tenant_id`,`merchant_id`,`merchant_order_no`),
  KEY `idx_merchant_wallet_statement_biz` (`tenant_id`,`biz_type`,`biz_no`),
  KEY `idx_merchant_wallet_statement_journal` (`tenant_id`,`journal_no`),
  KEY `idx_merchant_wallet_statement_account_posted` (`tenant_id`,`account_id`,`posted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商户钱包可见流水';

SET FOREIGN_KEY_CHECKS = 1;
