-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS tg_account CASCADE;
CREATE TABLE tg_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  bot_id bigint NOT NULL,
  tg_user_id bigint NOT NULL,
  tg_username varchar(64) NULL,
  language_code varchar(16) NULL,
  user_id bigint NOT NULL,
  subject_id bigint NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  bound_at timestamp(3) NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_tg_account PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_tg_account_uk_tg_account_bot_user ON tg_account (bot_id, tg_user_id);
CREATE INDEX idx_tg_account_idx_tg_account_user ON tg_account (user_id, status);
CREATE INDEX idx_tg_account_idx_tg_account_subject ON tg_account (subject_id, status);
CREATE INDEX idx_tg_account_idx_tg_account_tenant ON tg_account (tenant_id, status);

DROP TABLE IF EXISTS tg_bot CASCADE;
CREATE TABLE tg_bot (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_scope varchar(16) NOT NULL DEFAULT 'PLATFORM',
  tenant_id bigint NULL DEFAULT 0,
  bot_no varchar(64) NOT NULL,
  name varchar(128) NULL,
  username varchar(64) NOT NULL,
  bot_user_id bigint NULL,
  token_cipher varchar(512) NOT NULL,
  token_hash varchar(128) NOT NULL,
  secret_token varchar(128) NULL,
  webhook_url varchar(512) NULL,
  mode varchar(16) NOT NULL DEFAULT 'WEBHOOK',
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_tg_bot PRIMARY KEY (id),
  CONSTRAINT chk_tg_bot_1 CHECK (owner_scope in ('PLATFORM','TENANT')),
  CONSTRAINT chk_tg_bot_2 CHECK ((owner_scope <> 'TENANT') or (tenant_id is not null))
);
CREATE UNIQUE INDEX uk_tg_bot_uk_tg_bot_no ON tg_bot (bot_no);
CREATE UNIQUE INDEX uk_tg_bot_uk_tg_bot_token ON tg_bot (token_hash);
CREATE INDEX idx_tg_bot_idx_tg_bot_tenant ON tg_bot (tenant_id, status);

DROP TABLE IF EXISTS tg_chat CASCADE;
CREATE TABLE tg_chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NULL DEFAULT 0,
  merchant_id bigint NULL DEFAULT 0,
  bot_id bigint NOT NULL,
  chat_id bigint NOT NULL,
  chat_type varchar(16) NOT NULL,
  title varchar(255) NULL,
  purpose varchar(16) NOT NULL DEFAULT 'NOTIFY',
  event_types varchar(512) NULL,
  lang varchar(16) NOT NULL DEFAULT 'en-US',
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_tg_chat PRIMARY KEY (id),
  CONSTRAINT chk_tg_chat_1 CHECK (chat_type in ('PRIVATE','GROUP','SUPERGROUP','CHANNEL'))
);
CREATE UNIQUE INDEX uk_tg_chat_uk_tg_chat_bot_chat ON tg_chat (bot_id, chat_id);
CREATE INDEX idx_tg_chat_idx_tg_chat_tenant ON tg_chat (tenant_id, merchant_id, status);

DROP TABLE IF EXISTS tg_message_task CASCADE;
CREATE TABLE tg_message_task (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 0,
  merchant_id bigint NOT NULL DEFAULT 0,
  bot_id bigint NOT NULL,
  chat_id bigint NOT NULL,
  task_no varchar(128) NOT NULL,
  biz_type varchar(64) NULL,
  biz_no varchar(128) NULL,
  event_type varchar(64) NULL,
  source_event_id varchar(64) NULL,
  parse_mode varchar(16) NOT NULL DEFAULT 'HTML',
  content text NOT NULL,
  payload_json json NULL,
  status varchar(32) NOT NULL DEFAULT 'INIT',
  retry_count integer NOT NULL DEFAULT 0,
  max_retry_count integer NOT NULL DEFAULT 8,
  next_retry_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  tg_message_id bigint NULL,
  last_error_code integer NULL,
  last_error_msg varchar(1024) NULL,
  last_attempt_at timestamp(3) NULL,
  locked_by varchar(128) NULL,
  lock_until timestamp(3) NULL,
  success_at timestamp(3) NULL,
  dead_at timestamp(3) NULL,
  trace_id varchar(128) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_tg_message_task PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_tg_message_task_uk_tg_msg_task_no ON tg_message_task (tenant_id, task_no);
CREATE UNIQUE INDEX uk_tg_message_task_uk_tg_msg_source ON tg_message_task (bot_id, chat_id, source_event_id);
CREATE INDEX idx_tg_message_task_idx_tg_msg_scan ON tg_message_task (status, next_retry_at, id);
CREATE INDEX idx_tg_message_task_idx_tg_msg_lock ON tg_message_task (lock_until, locked_by);
CREATE INDEX idx_tg_message_task_idx_tg_msg_biz ON tg_message_task (tenant_id, biz_type, biz_no);

DROP TABLE IF EXISTS tg_update_log CASCADE;
CREATE TABLE tg_update_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bot_id bigint NOT NULL,
  update_id bigint NOT NULL,
  tg_user_id bigint NULL,
  chat_id bigint NULL,
  update_type varchar(32) NULL,
  command varchar(64) NULL,
  raw_json json NOT NULL,
  handle_status smallint NOT NULL DEFAULT 0,
  error_msg varchar(1024) NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_tg_update_log PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_tg_update_log_uk_tg_update ON tg_update_log (bot_id, update_id);
CREATE INDEX idx_tg_update_log_idx_tg_update_chat ON tg_update_log (chat_id, created_at);
