-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS merchant_balance_adjust_order CASCADE;
CREATE TABLE merchant_balance_adjust_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NOT NULL,
  adjust_order_no varchar(128) NOT NULL,
  adjust_type varchar(32) NOT NULL,
  source_type varchar(32) NOT NULL DEFAULT 'MANUAL',
  currency varchar(16) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'CREATED',
  reason varchar(512) NULL,
  related_order_no varchar(128) NULL,
  reverse_of_journal_no varchar(64) NULL,
  ledger_journal_no varchar(64) NULL,
  trace_id varchar(128) NULL,
  posted_at timestamp(3) NULL,
  operator_type varchar(32) NOT NULL DEFAULT 'ADMIN',
  operator_id varchar(128) NULL,
  extra_json json NULL,
  version integer NOT NULL DEFAULT 0,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_balance_adjust_order PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_balance_adjust_order_uk_mba_order_no ON merchant_balance_adjust_order (tenant_id, adjust_order_no);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_merchant_created ON merchant_balance_adjust_order (tenant_id, merchant_id, created_at);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_type_status ON merchant_balance_adjust_order (tenant_id, adjust_type, status, created_at);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_journal ON merchant_balance_adjust_order (tenant_id, ledger_journal_no);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_related_order ON merchant_balance_adjust_order (tenant_id, related_order_no);
