-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. Navicat metadata is intentionally omitted.

DROP TABLE IF EXISTS merchant_balance_adjust_order CASCADE;
CREATE TABLE merchant_balance_adjust_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NOT NULL,
  adjust_order_no varchar(128) NOT NULL,
  adjust_type varchar(32) NOT NULL,
  source_type varchar(32) NOT NULL DEFAULT 'MANUAL',
  currency varchar(16) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'CREATED',
  reason varchar(512) NULL,
  related_order_no varchar(128) NULL,
  reverse_of_journal_no varchar(64) NULL,
  ledger_journal_no varchar(64) NULL,
  trace_id varchar(128) NULL,
  posted_at timestamp(3) NULL,
  operator_type varchar(32) NOT NULL DEFAULT 'ADMIN',
  operator_id varchar(128) NULL,
  extra_json json NULL,
  version integer NOT NULL DEFAULT 0,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_balance_adjust_order PRIMARY KEY (id)
);
COMMENT ON TABLE merchant_balance_adjust_order IS '商户余额调整单';
COMMENT ON COLUMN merchant_balance_adjust_order.id IS '主键ID';
COMMENT ON COLUMN merchant_balance_adjust_order.tenant_id IS '租户ID';
COMMENT ON COLUMN merchant_balance_adjust_order.merchant_id IS '商户ID';
COMMENT ON COLUMN merchant_balance_adjust_order.merchant_no IS '商户号快照';
COMMENT ON COLUMN merchant_balance_adjust_order.adjust_order_no IS '余额调整单号';
COMMENT ON COLUMN merchant_balance_adjust_order.adjust_type IS '调整类型: RECHARGE/DEDUCT/REVERSE/SUPPLEMENT';
COMMENT ON COLUMN merchant_balance_adjust_order.source_type IS '来源: MANUAL/SYSTEM/API';
COMMENT ON COLUMN merchant_balance_adjust_order.currency IS '币种';
COMMENT ON COLUMN merchant_balance_adjust_order.amount IS '调整金额，永远为正数';
COMMENT ON COLUMN merchant_balance_adjust_order.status IS '状态: CREATED/POSTED/FAILED';
COMMENT ON COLUMN merchant_balance_adjust_order.reason IS '调整原因';
COMMENT ON COLUMN merchant_balance_adjust_order.related_order_no IS '关联业务单号';
COMMENT ON COLUMN merchant_balance_adjust_order.reverse_of_journal_no IS '冲正来源凭证号';
COMMENT ON COLUMN merchant_balance_adjust_order.ledger_journal_no IS '账本凭证号';
COMMENT ON COLUMN merchant_balance_adjust_order.trace_id IS '链路追踪ID';
COMMENT ON COLUMN merchant_balance_adjust_order.posted_at IS '入账时间';
COMMENT ON COLUMN merchant_balance_adjust_order.operator_type IS '操作方类型: ADMIN/SYSTEM/API';
COMMENT ON COLUMN merchant_balance_adjust_order.operator_id IS '操作方ID';
COMMENT ON COLUMN merchant_balance_adjust_order.extra_json IS '扩展JSON';
COMMENT ON COLUMN merchant_balance_adjust_order.version IS '乐观锁版本';
COMMENT ON COLUMN merchant_balance_adjust_order.remark IS '备注';
COMMENT ON COLUMN merchant_balance_adjust_order.created_by IS '创建人ID';
COMMENT ON COLUMN merchant_balance_adjust_order.created_at IS '创建时间';
COMMENT ON COLUMN merchant_balance_adjust_order.updated_by IS '更新人ID';
COMMENT ON COLUMN merchant_balance_adjust_order.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_merchant_balance_adjust_order_uk_mba_order_no ON merchant_balance_adjust_order (tenant_id, adjust_order_no);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_merchant_created ON merchant_balance_adjust_order (tenant_id, merchant_id, created_at);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_type_status ON merchant_balance_adjust_order (tenant_id, adjust_type, status, created_at);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_journal ON merchant_balance_adjust_order (tenant_id, ledger_journal_no);
CREATE INDEX idx_merchant_balance_adjust_order_idx_mba_related_order ON merchant_balance_adjust_order (tenant_id, related_order_no);
