/*
 Navicat Premium Dump SQL

 Source Server         : 涓汉鏁版嵁搴?HK)
 Source Server Type    : MySQL
 Source Server Version : 80036 (8.0.36)
 Source Host           : rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306
 Source Schema         : gk-union

 Target Server Type    : MySQL
 Target Server Version : 80036 (8.0.36)
 File Encoding         : 65001

 Date: 10/06/2026 12:31:23
*/


-- ----------------------------
-- Table structure for ledger_account
-- ----------------------------
DROP TABLE IF EXISTS "ledger_account";
CREATE TABLE "ledger_account"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "account_no" varchar(64) NOT NULL,
  "owner_type" varchar(32) NOT NULL,
  "owner_id" bigint NOT NULL,
  "account_type" varchar(64) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "normal_side" varchar(16) NOT NULL,
  "allow_negative" SMALLINT NOT NULL DEFAULT 0,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_ledger_account_no" ON "ledger_account" ("account_no" ASC);
CREATE UNIQUE INDEX "uk_ledger_account_owner" ON "ledger_account" ("tenant_id" ASC, "owner_type" ASC, "owner_id" ASC, "account_type" ASC, "currency" ASC);
CREATE INDEX "idx_ledger_account_owner_currency" ON "ledger_account" ("tenant_id" ASC, "owner_type" ASC, "owner_id" ASC, "currency" ASC);
CREATE INDEX "idx_ledger_account_type" ON "ledger_account" ("tenant_id" ASC, "account_type" ASC, "currency" ASC, "status" ASC);

-- ----------------------------
-- Table structure for ledger_balance
-- ----------------------------
DROP TABLE IF EXISTS "ledger_balance";
CREATE TABLE "ledger_balance"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "account_id" bigint NOT NULL,
  "account_no" varchar(64) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "balance" decimal(28, 8) NOT NULL DEFAULT 0.00000000,
  "debit_total" decimal(28, 8) NOT NULL DEFAULT 0.00000000,
  "credit_total" decimal(28, 8) NOT NULL DEFAULT 0.00000000,
  "version" int NOT NULL DEFAULT 0,
  "last_entry_id" bigint NULL DEFAULT NULL,
  "last_journal_no" varchar(64) NULL DEFAULT NULL,
  "last_posted_at" TIMESTAMP NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_ledger_balance_account" ON "ledger_balance" ("tenant_id" ASC, "account_id" ASC);
CREATE UNIQUE INDEX "uk_ledger_balance_account_no" ON "ledger_balance" ("tenant_id" ASC, "account_no" ASC);
CREATE INDEX "idx_ledger_balance_currency" ON "ledger_balance" ("tenant_id" ASC, "currency" ASC);

-- ----------------------------
-- Table structure for ledger_entry
-- ----------------------------
DROP TABLE IF EXISTS "ledger_entry";
CREATE TABLE "ledger_entry"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "journal_id" bigint NOT NULL,
  "journal_no" varchar(64) NOT NULL,
  "entry_no" int NOT NULL,
  "account_id" bigint NOT NULL,
  "account_no" varchar(64) NOT NULL,
  "owner_type" varchar(32) NOT NULL,
  "owner_id" bigint NOT NULL,
  "account_type" varchar(64) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "normal_side" varchar(16) NOT NULL,
  "direction" varchar(16) NOT NULL,
  "amount" decimal(24, 8) NOT NULL,
  "balance_change" decimal(24, 8) NOT NULL,
  "balance_before" decimal(24, 8) NOT NULL,
  "balance_after" decimal(24, 8) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "summary" varchar(256) NULL DEFAULT NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_ledger_entry_journal_no" ON "ledger_entry" ("tenant_id" ASC, "journal_id" ASC, "entry_no" ASC);
CREATE INDEX "idx_ledger_entry_journal" ON "ledger_entry" ("tenant_id" ASC, "journal_no" ASC);
CREATE INDEX "idx_ledger_entry_account_created" ON "ledger_entry" ("tenant_id" ASC, "account_id" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_entry_owner_created" ON "ledger_entry" ("tenant_id" ASC, "owner_type" ASC, "owner_id" ASC, "currency" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_entry_account_type_created" ON "ledger_entry" ("tenant_id" ASC, "account_type" ASC, "currency" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_entry_biz" ON "ledger_entry" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC, "event_type" ASC);

-- ----------------------------
-- Table structure for ledger_hold
-- ----------------------------
DROP TABLE IF EXISTS "ledger_hold";
CREATE TABLE "ledger_hold"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "hold_no" varchar(64) NOT NULL,
  "owner_type" varchar(32) NOT NULL,
  "owner_id" bigint NOT NULL,
  "currency" varchar(16) NOT NULL,
  "available_account_id" bigint NOT NULL,
  "available_account_no" varchar(64) NOT NULL,
  "frozen_account_id" bigint NOT NULL,
  "frozen_account_no" varchar(64) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NOT NULL,
  "hold_reason" varchar(64) NOT NULL,
  "hold_scope" varchar(64) NOT NULL DEFAULT 'ORDER',
  "hold_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "released_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "consumed_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "remaining_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "status" varchar(32) NOT NULL DEFAULT 'HOLDING',
  "hold_journal_no" varchar(64) NULL DEFAULT NULL,
  "last_release_journal_no" varchar(64) NULL DEFAULT NULL,
  "consume_journal_no" varchar(64) NULL DEFAULT NULL,
  "expired_at" TIMESTAMP NULL DEFAULT NULL,
  "reason" varchar(512) NULL DEFAULT NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_ledger_hold_no" ON "ledger_hold" ("tenant_id" ASC, "hold_no" ASC);
CREATE UNIQUE INDEX "uk_ledger_hold_biz_scope" ON "ledger_hold" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC, "hold_scope" ASC);
CREATE INDEX "idx_ledger_hold_scope" ON "ledger_hold" ("tenant_id" ASC, "hold_scope" ASC, "status" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_hold_owner_status" ON "ledger_hold" ("tenant_id" ASC, "owner_type" ASC, "owner_id" ASC, "currency" ASC, "status" ASC);
CREATE INDEX "idx_ledger_hold_expired" ON "ledger_hold" ("tenant_id" ASC, "status" ASC, "expired_at" ASC);

-- ----------------------------
-- Table structure for ledger_journal
-- ----------------------------
DROP TABLE IF EXISTS "ledger_journal";
CREATE TABLE "ledger_journal"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "journal_no" varchar(64) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "total_amount" decimal(24, 8) NOT NULL,
  "entry_count" int NOT NULL DEFAULT 0,
  "idempotency_key" varchar(128) NOT NULL,
  "status" varchar(32) NOT NULL DEFAULT 'POSTED',
  "reverse_of_journal_no" varchar(64) NULL DEFAULT NULL,
  "reversed_by_journal_no" varchar(64) NULL DEFAULT NULL,
  "source_type" varchar(32) NOT NULL DEFAULT 'SYSTEM',
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "posted_at" TIMESTAMP NULL DEFAULT NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_ledger_journal_no" ON "ledger_journal" ("tenant_id" ASC, "journal_no" ASC);
CREATE UNIQUE INDEX "uk_ledger_journal_idempotency" ON "ledger_journal" ("tenant_id" ASC, "idempotency_key" ASC);
CREATE UNIQUE INDEX "uk_ledger_journal_biz_event" ON "ledger_journal" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC, "event_type" ASC);
CREATE INDEX "idx_ledger_journal_biz" ON "ledger_journal" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC);
CREATE INDEX "idx_ledger_journal_source" ON "ledger_journal" ("tenant_id" ASC, "source_type" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_journal_status_created" ON "ledger_journal" ("tenant_id" ASC, "status" ASC, "created_at" ASC);
CREATE INDEX "idx_ledger_journal_posted" ON "ledger_journal" ("tenant_id" ASC, "posted_at" ASC);
