-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS ledger_account CASCADE;
CREATE TABLE ledger_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  normal_side varchar(16) NOT NULL,
  allow_negative smallint NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_account PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_ledger_account_uk_ledger_account_owner ON ledger_account (tenant_id, owner_type, owner_id, account_type, currency);
CREATE UNIQUE INDEX uk_ledger_account_uk_ledger_account_no ON ledger_account (tenant_id, account_no);
CREATE INDEX idx_ledger_account_idx_ledger_account_owner_currency ON ledger_account (tenant_id, owner_type, owner_id, currency);
CREATE INDEX idx_ledger_account_idx_ledger_account_type ON ledger_account (tenant_id, account_type, currency, status);

DROP TABLE IF EXISTS ledger_balance CASCADE;
CREATE TABLE ledger_balance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  balance numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  debit_total numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  credit_total numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  version integer NOT NULL DEFAULT 0,
  last_entry_id bigint NULL,
  last_journal_no varchar(64) NULL,
  last_posted_at timestamp(3) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_balance PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_ledger_balance_uk_ledger_balance_account ON ledger_balance (tenant_id, account_id);
CREATE UNIQUE INDEX uk_ledger_balance_uk_ledger_balance_account_no ON ledger_balance (tenant_id, account_no);
CREATE INDEX idx_ledger_balance_idx_ledger_balance_currency ON ledger_balance (tenant_id, currency);

DROP TABLE IF EXISTS ledger_entry CASCADE;
CREATE TABLE ledger_entry (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  journal_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  entry_no integer NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  normal_side varchar(16) NOT NULL,
  direction varchar(16) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  balance_change numeric(24, 8) NOT NULL,
  balance_before numeric(24, 8) NOT NULL,
  balance_after numeric(24, 8) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  event_type varchar(64) NOT NULL,
  summary varchar(256) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_entry PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_ledger_entry_uk_ledger_entry_journal_no ON ledger_entry (tenant_id, journal_id, entry_no);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_journal ON ledger_entry (tenant_id, journal_no);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_account_created ON ledger_entry (tenant_id, account_id, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_owner_created ON ledger_entry (tenant_id, owner_type, owner_id, currency, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_account_type_created ON ledger_entry (tenant_id, account_type, currency, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_biz ON ledger_entry (tenant_id, biz_type, biz_no, event_type);

DROP TABLE IF EXISTS ledger_hold CASCADE;
CREATE TABLE ledger_hold (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  hold_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  currency varchar(16) NOT NULL,
  available_account_id bigint NOT NULL,
  available_account_no varchar(64) NOT NULL,
  frozen_account_id bigint NOT NULL,
  frozen_account_no varchar(64) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  hold_reason varchar(64) NOT NULL,
  hold_scope varchar(64) NOT NULL DEFAULT 'ORDER',
  hold_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  released_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  consumed_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  remaining_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  status varchar(32) NOT NULL DEFAULT 'HOLDING',
  hold_journal_no varchar(64) NULL,
  last_release_journal_no varchar(64) NULL,
  consume_journal_no varchar(64) NULL,
  expired_at timestamp(3) NULL,
  reason varchar(512) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_hold PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_ledger_hold_uk_ledger_hold_no ON ledger_hold (tenant_id, hold_no);
CREATE UNIQUE INDEX uk_ledger_hold_uk_ledger_hold_biz_scope ON ledger_hold (tenant_id, biz_type, biz_no, hold_scope);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_scope ON ledger_hold (tenant_id, hold_scope, status, created_at);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_owner_status ON ledger_hold (tenant_id, owner_type, owner_id, currency, status);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_expired ON ledger_hold (tenant_id, status, expired_at);

DROP TABLE IF EXISTS ledger_journal CASCADE;
CREATE TABLE ledger_journal (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  event_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  total_amount numeric(24, 8) NOT NULL,
  entry_count integer NOT NULL DEFAULT 0,
  idempotency_key varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'POSTED',
  reverse_of_journal_no varchar(64) NULL,
  reversed_by_journal_no varchar(64) NULL,
  source_type varchar(32) NOT NULL DEFAULT 'SYSTEM',
  trace_id varchar(128) NULL,
  posted_at timestamp(3) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_journal PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_no ON ledger_journal (tenant_id, journal_no);
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_idempotency ON ledger_journal (tenant_id, idempotency_key);
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_biz_event ON ledger_journal (tenant_id, biz_type, biz_no, event_type);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_biz ON ledger_journal (tenant_id, biz_type, biz_no);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_source ON ledger_journal (tenant_id, source_type, created_at);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_status_created ON ledger_journal (tenant_id, status, created_at);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_posted ON ledger_journal (tenant_id, posted_at);

DROP TABLE IF EXISTS merchant_wallet_statement CASCADE;
CREATE TABLE merchant_wallet_statement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  statement_no varchar(64) NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NULL,
  merchant_app_id bigint NULL,
  journal_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  entry_id bigint NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  merchant_order_no varchar(128) NULL,
  event_type varchar(64) NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  effect_type varchar(32) NOT NULL,
  biz_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  net_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_change numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_before numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_after numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  source_type varchar(32) NOT NULL DEFAULT 'ORDER',
  status varchar(32) NOT NULL DEFAULT 'POSTED',
  posted_at timestamp(3) NOT NULL,
  trace_id varchar(128) NULL,
  summary varchar(256) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_wallet_statement PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_merchant_wallet_statement_uk_merchant_wallet_statement_no ON merchant_wallet_statement (tenant_id, statement_no);
CREATE UNIQUE INDEX uk_merchant_wallet_statement_uk_merchant_wallet_sta_0adef8a4 ON merchant_wallet_statement (tenant_id, entry_id);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_e7930d21 ON merchant_wallet_statement (tenant_id, merchant_id, posted_at);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_b64d5b75 ON merchant_wallet_statement (tenant_id, merchant_id, merchant_order_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_72d539f9 ON merchant_wallet_statement (tenant_id, biz_type, biz_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_bcc33bc5 ON merchant_wallet_statement (tenant_id, journal_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_0cf97682 ON merchant_wallet_statement (tenant_id, account_id, posted_at);
