-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. Navicat metadata is intentionally omitted.

DROP TABLE IF EXISTS ledger_account CASCADE;
CREATE TABLE ledger_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  normal_side varchar(16) NOT NULL,
  allow_negative smallint NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_account PRIMARY KEY (id)
);
COMMENT ON TABLE ledger_account IS '账务账户';
COMMENT ON COLUMN ledger_account.id IS '主键ID';
COMMENT ON COLUMN ledger_account.tenant_id IS '租户ID';
COMMENT ON COLUMN ledger_account.account_no IS '账户编号';
COMMENT ON COLUMN ledger_account.owner_type IS '资金主体类型: PLATFORM/TENANT/MERCHANT/PSP/SYSTEM';
COMMENT ON COLUMN ledger_account.owner_id IS '资金主体ID; 系统级账户可使用0';
COMMENT ON COLUMN ledger_account.account_type IS '账户类型: MERCHANT_AVAILABLE/MERCHANT_PENDING_SETTLE/MERCHANT_FROZEN/PSP_AVAILABLE/PSP_CLEARING等';
COMMENT ON COLUMN ledger_account.currency IS '币种: USD/CNY/BRL/INR等';
COMMENT ON COLUMN ledger_account.normal_side IS '账户余额方向: DEBIT/CREDIT';
COMMENT ON COLUMN ledger_account.allow_negative IS '是否允许负余额: 0否 1是';
COMMENT ON COLUMN ledger_account.status IS '状态: 1正常 2暂停 3停用';
COMMENT ON COLUMN ledger_account.remark IS '备注';
COMMENT ON COLUMN ledger_account.created_by IS '创建人ID';
COMMENT ON COLUMN ledger_account.created_at IS '创建时间';
COMMENT ON COLUMN ledger_account.updated_by IS '更新人ID';
COMMENT ON COLUMN ledger_account.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_ledger_account_uk_ledger_account_owner ON ledger_account (tenant_id, owner_type, owner_id, account_type, currency);
CREATE UNIQUE INDEX uk_ledger_account_uk_ledger_account_no ON ledger_account (tenant_id, account_no);
CREATE INDEX idx_ledger_account_idx_ledger_account_owner_currency ON ledger_account (tenant_id, owner_type, owner_id, currency);
CREATE INDEX idx_ledger_account_idx_ledger_account_type ON ledger_account (tenant_id, account_type, currency, status);

DROP TABLE IF EXISTS ledger_balance CASCADE;
CREATE TABLE ledger_balance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  balance numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  debit_total numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  credit_total numeric(28, 8) NOT NULL DEFAULT 0.00000000,
  version integer NOT NULL DEFAULT 0,
  last_entry_id bigint NULL,
  last_journal_no varchar(64) NULL,
  last_posted_at timestamp(3) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_balance PRIMARY KEY (id)
);
COMMENT ON TABLE ledger_balance IS '账务余额缓存';
COMMENT ON COLUMN ledger_balance.id IS '主键ID';
COMMENT ON COLUMN ledger_balance.tenant_id IS '租户ID';
COMMENT ON COLUMN ledger_balance.account_id IS '账户ID';
COMMENT ON COLUMN ledger_balance.account_no IS '账户编号';
COMMENT ON COLUMN ledger_balance.currency IS '币种';
COMMENT ON COLUMN ledger_balance.balance IS '当前余额';
COMMENT ON COLUMN ledger_balance.debit_total IS '借方累计发生额';
COMMENT ON COLUMN ledger_balance.credit_total IS '贷方累计发生额';
COMMENT ON COLUMN ledger_balance.version IS '乐观锁版本号';
COMMENT ON COLUMN ledger_balance.last_entry_id IS '最后一条分录ID';
COMMENT ON COLUMN ledger_balance.last_journal_no IS '最后一张凭证号';
COMMENT ON COLUMN ledger_balance.last_posted_at IS '最后过账时间';
COMMENT ON COLUMN ledger_balance.created_by IS '创建人ID';
COMMENT ON COLUMN ledger_balance.created_at IS '创建时间';
COMMENT ON COLUMN ledger_balance.updated_by IS '更新人ID';
COMMENT ON COLUMN ledger_balance.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_ledger_balance_uk_ledger_balance_account ON ledger_balance (tenant_id, account_id);
CREATE UNIQUE INDEX uk_ledger_balance_uk_ledger_balance_account_no ON ledger_balance (tenant_id, account_no);
CREATE INDEX idx_ledger_balance_idx_ledger_balance_currency ON ledger_balance (tenant_id, currency);

DROP TABLE IF EXISTS ledger_entry CASCADE;
CREATE TABLE ledger_entry (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  journal_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  entry_no integer NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  normal_side varchar(16) NOT NULL,
  direction varchar(16) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  balance_change numeric(24, 8) NOT NULL,
  balance_before numeric(24, 8) NOT NULL,
  balance_after numeric(24, 8) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  event_type varchar(64) NOT NULL,
  summary varchar(256) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_entry PRIMARY KEY (id)
);
COMMENT ON TABLE ledger_entry IS '账务账变流水/会计分录';
COMMENT ON COLUMN ledger_entry.id IS '主键ID';
COMMENT ON COLUMN ledger_entry.tenant_id IS '租户ID';
COMMENT ON COLUMN ledger_entry.journal_id IS '凭证ID';
COMMENT ON COLUMN ledger_entry.journal_no IS '凭证号';
COMMENT ON COLUMN ledger_entry.entry_no IS '凭证内分录序号';
COMMENT ON COLUMN ledger_entry.account_id IS '账户ID';
COMMENT ON COLUMN ledger_entry.account_no IS '账户编号';
COMMENT ON COLUMN ledger_entry.owner_type IS '资金主体类型快照';
COMMENT ON COLUMN ledger_entry.owner_id IS '资金主体ID快照';
COMMENT ON COLUMN ledger_entry.account_type IS '账户类型快照';
COMMENT ON COLUMN ledger_entry.currency IS '币种';
COMMENT ON COLUMN ledger_entry.normal_side IS '账户余额方向快照: DEBIT/CREDIT';
COMMENT ON COLUMN ledger_entry.direction IS '记账方向: DEBIT/CREDIT';
COMMENT ON COLUMN ledger_entry.amount IS '分录金额，永远为正数';
COMMENT ON COLUMN ledger_entry.balance_change IS '余额变动金额，可正可负';
COMMENT ON COLUMN ledger_entry.balance_before IS '变动前余额';
COMMENT ON COLUMN ledger_entry.balance_after IS '变动后余额';
COMMENT ON COLUMN ledger_entry.biz_type IS '业务类型快照';
COMMENT ON COLUMN ledger_entry.biz_id IS '业务ID快照';
COMMENT ON COLUMN ledger_entry.biz_no IS '业务编号快照';
COMMENT ON COLUMN ledger_entry.event_type IS '业务事件快照';
COMMENT ON COLUMN ledger_entry.summary IS '摘要';
COMMENT ON COLUMN ledger_entry.remark IS '备注';
COMMENT ON COLUMN ledger_entry.created_by IS '创建人ID';
COMMENT ON COLUMN ledger_entry.created_at IS '创建时间';
COMMENT ON COLUMN ledger_entry.updated_by IS '更新人ID';
COMMENT ON COLUMN ledger_entry.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_ledger_entry_uk_ledger_entry_journal_no ON ledger_entry (tenant_id, journal_id, entry_no);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_journal ON ledger_entry (tenant_id, journal_no);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_account_created ON ledger_entry (tenant_id, account_id, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_owner_created ON ledger_entry (tenant_id, owner_type, owner_id, currency, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_account_type_created ON ledger_entry (tenant_id, account_type, currency, created_at);
CREATE INDEX idx_ledger_entry_idx_ledger_entry_biz ON ledger_entry (tenant_id, biz_type, biz_no, event_type);

DROP TABLE IF EXISTS ledger_hold CASCADE;
CREATE TABLE ledger_hold (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  hold_no varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id bigint NOT NULL,
  currency varchar(16) NOT NULL,
  available_account_id bigint NOT NULL,
  available_account_no varchar(64) NOT NULL,
  frozen_account_id bigint NOT NULL,
  frozen_account_no varchar(64) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  hold_reason varchar(64) NOT NULL,
  hold_scope varchar(64) NOT NULL DEFAULT 'ORDER',
  hold_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  released_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  consumed_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  remaining_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  status varchar(32) NOT NULL DEFAULT 'HOLDING',
  hold_journal_no varchar(64) NULL,
  last_release_journal_no varchar(64) NULL,
  consume_journal_no varchar(64) NULL,
  expired_at timestamp(3) NULL,
  reason varchar(512) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_hold PRIMARY KEY (id)
);
COMMENT ON TABLE ledger_hold IS '账务冻结明细';
COMMENT ON COLUMN ledger_hold.id IS '主键ID';
COMMENT ON COLUMN ledger_hold.tenant_id IS '租户ID';
COMMENT ON COLUMN ledger_hold.hold_no IS '冻结编号';
COMMENT ON COLUMN ledger_hold.owner_type IS '资金主体类型: MERCHANT/PSP等';
COMMENT ON COLUMN ledger_hold.owner_id IS '资金主体ID';
COMMENT ON COLUMN ledger_hold.currency IS '币种';
COMMENT ON COLUMN ledger_hold.available_account_id IS '可用账户ID';
COMMENT ON COLUMN ledger_hold.available_account_no IS '可用账户编号';
COMMENT ON COLUMN ledger_hold.frozen_account_id IS '冻结账户ID';
COMMENT ON COLUMN ledger_hold.frozen_account_no IS '冻结账户编号';
COMMENT ON COLUMN ledger_hold.biz_type IS '业务类型: PAYOUT_ORDER/RISK_CONTROL/SECURITY_DEPOSIT/MANUAL_FREEZE等';
COMMENT ON COLUMN ledger_hold.biz_id IS '业务ID';
COMMENT ON COLUMN ledger_hold.biz_no IS '业务编号';
COMMENT ON COLUMN ledger_hold.hold_reason IS '冻结原因';
COMMENT ON COLUMN ledger_hold.hold_scope IS '冻结作用域: ORDER/RISK/DEPOSIT/MANUAL';
COMMENT ON COLUMN ledger_hold.hold_amount IS '冻结总金额';
COMMENT ON COLUMN ledger_hold.released_amount IS '已释放金额';
COMMENT ON COLUMN ledger_hold.consumed_amount IS '已消耗金额';
COMMENT ON COLUMN ledger_hold.remaining_amount IS '剩余冻结金额';
COMMENT ON COLUMN ledger_hold.status IS '状态: HOLDING/PART_RELEASED/RELEASED/CONSUMED/CANCELLED';
COMMENT ON COLUMN ledger_hold.hold_journal_no IS '冻结凭证号';
COMMENT ON COLUMN ledger_hold.last_release_journal_no IS '最后释放凭证号';
COMMENT ON COLUMN ledger_hold.consume_journal_no IS '消耗凭证号';
COMMENT ON COLUMN ledger_hold.expired_at IS '冻结过期时间';
COMMENT ON COLUMN ledger_hold.reason IS '原因说明';
COMMENT ON COLUMN ledger_hold.remark IS '备注';
COMMENT ON COLUMN ledger_hold.created_by IS '创建人ID';
COMMENT ON COLUMN ledger_hold.created_at IS '创建时间';
COMMENT ON COLUMN ledger_hold.updated_by IS '更新人ID';
COMMENT ON COLUMN ledger_hold.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_ledger_hold_uk_ledger_hold_no ON ledger_hold (tenant_id, hold_no);
CREATE UNIQUE INDEX uk_ledger_hold_uk_ledger_hold_biz_scope ON ledger_hold (tenant_id, biz_type, biz_no, hold_scope);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_scope ON ledger_hold (tenant_id, hold_scope, status, created_at);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_owner_status ON ledger_hold (tenant_id, owner_type, owner_id, currency, status);
CREATE INDEX idx_ledger_hold_idx_ledger_hold_expired ON ledger_hold (tenant_id, status, expired_at);

DROP TABLE IF EXISTS ledger_journal CASCADE;
CREATE TABLE ledger_journal (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  event_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  total_amount numeric(24, 8) NOT NULL,
  entry_count integer NOT NULL DEFAULT 0,
  idempotency_key varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'POSTED',
  reverse_of_journal_no varchar(64) NULL,
  reversed_by_journal_no varchar(64) NULL,
  source_type varchar(32) NOT NULL DEFAULT 'SYSTEM',
  trace_id varchar(128) NULL,
  posted_at timestamp(3) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_ledger_journal PRIMARY KEY (id)
);
COMMENT ON TABLE ledger_journal IS '账务记账凭证';
COMMENT ON COLUMN ledger_journal.id IS '主键ID';
COMMENT ON COLUMN ledger_journal.tenant_id IS '租户ID';
COMMENT ON COLUMN ledger_journal.journal_no IS '凭证号';
COMMENT ON COLUMN ledger_journal.biz_type IS '业务类型: PAY_ORDER/PAYOUT_ORDER/SETTLE_BATCH/RECON_ADJUST等';
COMMENT ON COLUMN ledger_journal.biz_id IS '业务ID';
COMMENT ON COLUMN ledger_journal.biz_no IS '业务编号';
COMMENT ON COLUMN ledger_journal.event_type IS '业务事件: PAY_SUCCESS/PAYOUT_FREEZE/PAYOUT_SUCCESS/PAYOUT_FAILED等';
COMMENT ON COLUMN ledger_journal.currency IS '币种';
COMMENT ON COLUMN ledger_journal.total_amount IS '凭证总金额';
COMMENT ON COLUMN ledger_journal.entry_count IS '分录数量';
COMMENT ON COLUMN ledger_journal.idempotency_key IS '幂等键';
COMMENT ON COLUMN ledger_journal.status IS '状态: POSTED/REVERSED';
COMMENT ON COLUMN ledger_journal.reverse_of_journal_no IS '冲正来源凭证号; 当前凭证为冲正凭证时填写';
COMMENT ON COLUMN ledger_journal.reversed_by_journal_no IS '冲正凭证号; 当前凭证被冲正后填写';
COMMENT ON COLUMN ledger_journal.source_type IS '记账来源: ORDER/SETTLE/RECON/MANUAL/SYSTEM';
COMMENT ON COLUMN ledger_journal.trace_id IS '链路追踪ID';
COMMENT ON COLUMN ledger_journal.posted_at IS '过账时间';
COMMENT ON COLUMN ledger_journal.remark IS '备注';
COMMENT ON COLUMN ledger_journal.created_by IS '创建人ID';
COMMENT ON COLUMN ledger_journal.created_at IS '创建时间';
COMMENT ON COLUMN ledger_journal.updated_by IS '更新人ID';
COMMENT ON COLUMN ledger_journal.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_no ON ledger_journal (tenant_id, journal_no);
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_idempotency ON ledger_journal (tenant_id, idempotency_key);
CREATE UNIQUE INDEX uk_ledger_journal_uk_ledger_journal_biz_event ON ledger_journal (tenant_id, biz_type, biz_no, event_type);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_biz ON ledger_journal (tenant_id, biz_type, biz_no);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_source ON ledger_journal (tenant_id, source_type, created_at);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_status_created ON ledger_journal (tenant_id, status, created_at);
CREATE INDEX idx_ledger_journal_idx_ledger_journal_posted ON ledger_journal (tenant_id, posted_at);

DROP TABLE IF EXISTS merchant_wallet_statement CASCADE;
CREATE TABLE merchant_wallet_statement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  statement_no varchar(64) NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NULL,
  merchant_app_id bigint NULL,
  journal_id bigint NOT NULL,
  journal_no varchar(64) NOT NULL,
  entry_id bigint NOT NULL,
  biz_type varchar(64) NOT NULL,
  biz_id bigint NULL,
  biz_no varchar(128) NOT NULL,
  merchant_order_no varchar(128) NULL,
  event_type varchar(64) NOT NULL,
  account_id bigint NOT NULL,
  account_no varchar(64) NOT NULL,
  account_type varchar(64) NOT NULL,
  currency varchar(16) NOT NULL,
  effect_type varchar(32) NOT NULL,
  biz_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  net_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_change numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_before numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  balance_after numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  source_type varchar(32) NOT NULL DEFAULT 'ORDER',
  status varchar(32) NOT NULL DEFAULT 'POSTED',
  posted_at timestamp(3) NOT NULL,
  trace_id varchar(128) NULL,
  summary varchar(256) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_merchant_wallet_statement PRIMARY KEY (id)
);
COMMENT ON TABLE merchant_wallet_statement IS '商户钱包可见流水';
COMMENT ON COLUMN merchant_wallet_statement.id IS '主键ID';
COMMENT ON COLUMN merchant_wallet_statement.tenant_id IS '租户ID';
COMMENT ON COLUMN merchant_wallet_statement.statement_no IS '商户钱包流水号';
COMMENT ON COLUMN merchant_wallet_statement.merchant_id IS '商户ID';
COMMENT ON COLUMN merchant_wallet_statement.merchant_no IS '商户编号快照';
COMMENT ON COLUMN merchant_wallet_statement.merchant_app_id IS '商户应用ID快照';
COMMENT ON COLUMN merchant_wallet_statement.journal_id IS '账务凭证ID';
COMMENT ON COLUMN merchant_wallet_statement.journal_no IS '账务凭证号';
COMMENT ON COLUMN merchant_wallet_statement.entry_id IS '关联账务分录ID';
COMMENT ON COLUMN merchant_wallet_statement.biz_type IS '业务类型';
COMMENT ON COLUMN merchant_wallet_statement.biz_id IS '业务ID';
COMMENT ON COLUMN merchant_wallet_statement.biz_no IS '系统业务单号';
COMMENT ON COLUMN merchant_wallet_statement.merchant_order_no IS '商户订单号快照';
COMMENT ON COLUMN merchant_wallet_statement.event_type IS '账务事件';
COMMENT ON COLUMN merchant_wallet_statement.account_id IS '商户账户ID';
COMMENT ON COLUMN merchant_wallet_statement.account_no IS '商户账户号';
COMMENT ON COLUMN merchant_wallet_statement.account_type IS '商户账户类型';
COMMENT ON COLUMN merchant_wallet_statement.currency IS '币种';
COMMENT ON COLUMN merchant_wallet_statement.effect_type IS '流水效果: IN/OUT/FREEZE/UNFREEZE/ADJUST';
COMMENT ON COLUMN merchant_wallet_statement.biz_amount IS '业务金额/订单本金';
COMMENT ON COLUMN merchant_wallet_statement.fee_amount IS '商户手续费';
COMMENT ON COLUMN merchant_wallet_statement.net_amount IS '商户净额/本次业务影响金额';
COMMENT ON COLUMN merchant_wallet_statement.balance_change IS '余额变化金额';
COMMENT ON COLUMN merchant_wallet_statement.balance_before IS '变动前余额';
COMMENT ON COLUMN merchant_wallet_statement.balance_after IS '变动后余额';
COMMENT ON COLUMN merchant_wallet_statement.source_type IS '来源: ORDER/SETTLE/RECON/MANUAL/SYSTEM';
COMMENT ON COLUMN merchant_wallet_statement.status IS '状态: POSTED/REVERSED';
COMMENT ON COLUMN merchant_wallet_statement.posted_at IS '入账时间';
COMMENT ON COLUMN merchant_wallet_statement.trace_id IS '链路追踪ID';
COMMENT ON COLUMN merchant_wallet_statement.summary IS '商户侧摘要';
COMMENT ON COLUMN merchant_wallet_statement.remark IS '备注';
COMMENT ON COLUMN merchant_wallet_statement.created_by IS '创建人ID';
COMMENT ON COLUMN merchant_wallet_statement.created_at IS '创建时间';
COMMENT ON COLUMN merchant_wallet_statement.updated_by IS '更新人ID';
COMMENT ON COLUMN merchant_wallet_statement.updated_at IS '更新时间';
CREATE UNIQUE INDEX uk_merchant_wallet_statement_uk_merchant_wallet_statement_no ON merchant_wallet_statement (tenant_id, statement_no);
CREATE UNIQUE INDEX uk_merchant_wallet_statement_uk_merchant_wallet_sta_0adef8a4 ON merchant_wallet_statement (tenant_id, entry_id);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_e7930d21 ON merchant_wallet_statement (tenant_id, merchant_id, posted_at);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_b64d5b75 ON merchant_wallet_statement (tenant_id, merchant_id, merchant_order_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_72d539f9 ON merchant_wallet_statement (tenant_id, biz_type, biz_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_bcc33bc5 ON merchant_wallet_statement (tenant_id, journal_no);
CREATE INDEX idx_merchant_wallet_statement_idx_merchant_wallet_s_0cf97682 ON merchant_wallet_statement (tenant_id, account_id, posted_at);
