/*
 Navicat Premium Dump SQL

 Source Server         : 涓汉鏁版嵁搴?HK)
 Source Server Type    : MySQL
 Source Server Version : 80036 (8.0.36)
 Source Host           : rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306
 Source Schema         : gk-union

 Target Server Type    : MySQL
 Target Server Version : 80036 (8.0.36)
 File Encoding         : 65001

 Date: 10/06/2026 12:31:23
*/


-- ----------------------------
-- Table structure for mq_consume_record
-- ----------------------------
DROP TABLE IF EXISTS "mq_consume_record";
CREATE TABLE "mq_consume_record"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "event_id" varchar(64) NOT NULL,
  "topic" varchar(128) NOT NULL,
  "tag" varchar(128) NOT NULL,
  "message_key" varchar(256) NOT NULL,
  "consumer_group" varchar(128) NOT NULL,
  "consumer_name" varchar(128) NULL DEFAULT NULL,
  "consume_status" varchar(32) NOT NULL DEFAULT 'PROCESSING',
  "retry_count" int NOT NULL DEFAULT 0,
  "first_consumed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "last_consumed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "success_at" TIMESTAMP NULL DEFAULT NULL,
  "last_error_code" varchar(64) NULL DEFAULT NULL,
  "last_error_msg" varchar(1024) NULL DEFAULT NULL,
  "rocketmq_msg_id" varchar(128) NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_mq_consume_event_group" ON "mq_consume_record" ("event_id" ASC, "consumer_group" ASC);
CREATE INDEX "idx_mq_consume_message_group" ON "mq_consume_record" ("message_key" ASC, "consumer_group" ASC);
CREATE INDEX "idx_mq_consume_status" ON "mq_consume_record" ("consume_status" ASC, "last_consumed_at" ASC);
CREATE INDEX "idx_mq_consume_topic_tag" ON "mq_consume_record" ("topic" ASC, "tag" ASC, "consumer_group" ASC);

-- ----------------------------
-- Table structure for mq_outbox
-- ----------------------------
DROP TABLE IF EXISTS "mq_outbox";
CREATE TABLE "mq_outbox"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "event_id" varchar(64) NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "event_version" int NOT NULL DEFAULT 1,
  "source_service" varchar(64) NOT NULL,
  "aggregate_type" varchar(64) NOT NULL,
  "aggregate_id" bigint NULL DEFAULT NULL,
  "aggregate_no" varchar(128) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL DEFAULT NULL,
  "biz_no" varchar(128) NOT NULL,
  "topic" varchar(128) NOT NULL,
  "tag" varchar(128) NOT NULL,
  "message_key" varchar(256) NOT NULL,
  "sharding_key" varchar(128) NULL DEFAULT NULL,
  "producer_group" varchar(128) NULL DEFAULT NULL,
  "delay_level" int NULL DEFAULT NULL,
  "deliver_at" TIMESTAMP NULL DEFAULT NULL,
  "headers_json" json NULL,
  "payload_json" json NOT NULL,
  "publish_status" varchar(32) NOT NULL DEFAULT 'INIT',
  "consume_status" varchar(32) NOT NULL DEFAULT 'INIT',
  "retry_count" int NOT NULL DEFAULT 0,
  "max_retry_count" int NOT NULL DEFAULT 16,
  "next_retry_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "locked_by" varchar(128) NULL DEFAULT NULL,
  "locked_at" TIMESTAMP NULL DEFAULT NULL,
  "lock_until" TIMESTAMP NULL DEFAULT NULL,
  "rocketmq_msg_id" varchar(128) NULL DEFAULT NULL,
  "sent_at" TIMESTAMP NULL DEFAULT NULL,
  "consumed_at" TIMESTAMP NULL DEFAULT NULL,
  "dead_at" TIMESTAMP NULL DEFAULT NULL,
  "last_error_code" varchar(64) NULL DEFAULT NULL,
  "last_error_msg" varchar(1024) NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_mq_outbox_event" ON "mq_outbox" ("event_id" ASC);
CREATE UNIQUE INDEX "uk_mq_outbox_biz_event" ON "mq_outbox" ("tenant_id" ASC, "biz_type" ASC, "biz_no" ASC, "event_type" ASC);
CREATE INDEX "idx_mq_outbox_publish_scan" ON "mq_outbox" ("publish_status" ASC, "next_retry_at" ASC, "id" ASC);
CREATE INDEX "idx_mq_outbox_consume_scan" ON "mq_outbox" ("consume_status" ASC, "next_retry_at" ASC, "id" ASC);
CREATE INDEX "idx_mq_outbox_lock" ON "mq_outbox" ("lock_until" ASC, "locked_by" ASC);
CREATE INDEX "idx_mq_outbox_topic_tag" ON "mq_outbox" ("topic" ASC, "tag" ASC, "created_at" ASC);
CREATE INDEX "idx_mq_outbox_aggregate" ON "mq_outbox" ("tenant_id" ASC, "aggregate_type" ASC, "aggregate_no" ASC);
CREATE INDEX "idx_mq_outbox_message_key" ON "mq_outbox" ("message_key" ASC);
