-- gk-union PostgreSQL schema generated from the provided MySQL dump.
-- Source: pasted-text.txt. MySQL comments and Navicat metadata are intentionally omitted.

DROP TABLE IF EXISTS order_status_log CASCADE;
CREATE TABLE order_status_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NULL,
  log_no varchar(128) NOT NULL,
  direction varchar(32) NOT NULL,
  order_id bigint NOT NULL,
  order_no varchar(128) NOT NULL,
  from_status varchar(32) NULL,
  to_status varchar(32) NOT NULL,
  event_type varchar(64) NOT NULL,
  reason varchar(512) NULL,
  operator_type varchar(32) NOT NULL DEFAULT 'SYSTEM',
  operator_id varchar(128) NULL,
  request_id varchar(128) NULL,
  trace_id varchar(128) NULL,
  metadata_json json NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_order_status_log PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_order_status_log_uk_order_status_log_no ON order_status_log (tenant_id, log_no);
CREATE INDEX idx_order_status_log_idx_order_status_event ON order_status_log (tenant_id, event_type, created_at);
CREATE INDEX idx_order_status_log_idx_order_status_order ON order_status_log (tenant_id, direction, order_no, created_at);

DROP TABLE IF EXISTS payin_order CASCADE;
CREATE TABLE payin_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NOT NULL,
  merchant_app_id bigint NOT NULL,
  app_id varchar(64) NOT NULL,
  payin_order_no varchar(128) NOT NULL,
  merchant_order_no varchar(128) NOT NULL,
  idempotency_key varchar(128) NOT NULL,
  request_id varchar(128) NULL,
  order_source varchar(32) NOT NULL DEFAULT 'API',
  country_code varchar(8) NOT NULL,
  currency varchar(16) NOT NULL,
  method_code varchar(64) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  paid_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  merchant_fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  merchant_fee_rule_id bigint NULL,
  merchant_fee_snapshot_json json NULL,
  psp_fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  psp_fee_rule_id bigint NULL,
  psp_fee_snapshot_json json NULL,
  settle_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  subject varchar(256) NULL,
  description varchar(512) NULL,
  client_ip varchar(64) NULL,
  payer_json json NULL,
  notify_url varchar(512) NULL,
  return_url varchar(512) NULL,
  merchant_notify_status varchar(16) NULL,
  merchant_notify_at timestamp(3) NULL,
  merchant_notify_task_id bigint NULL,
  status varchar(32) NOT NULL DEFAULT 'CREATED',
  status_reason varchar(512) NULL,
  merchant_status_code varchar(64) NULL,
  merchant_status_reason varchar(512) NULL,
  expire_at timestamp(3) NULL,
  paid_at timestamp(3) NULL,
  closed_at timestamp(3) NULL,
  failed_at timestamp(3) NULL,
  payment_plan_catalog_id bigint NULL,
  payment_plan_version bigint NULL,
  payment_plan_bucket_id bigint NULL,
  payment_plan_route_option_id bigint NULL,
  route_rule_id bigint NULL,
  route_group_id bigint NULL,
  route_channel_id bigint NULL,
  route_snapshot_json json NULL,
  psp_id bigint NULL,
  psp_code varchar(64) NULL,
  psp_method_id bigint NULL,
  psp_method_code varchar(128) NULL,
  psp_account_id bigint NULL,
  psp_account_no varchar(128) NULL,
  psp_request_no varchar(128) NULL,
  psp_order_no varchar(128) NULL,
  psp_status varchar(64) NULL,
  psp_raw_status varchar(128) NULL,
  psp_pay_url varchar(1024) NULL,
  psp_pay_params_json json NULL,
  next_query_at timestamp(3) NULL,
  query_count integer NOT NULL DEFAULT 0,
  submitted_at timestamp(3) NULL,
  ledger_journal_no varchar(64) NULL,
  settle_status varchar(32) NOT NULL DEFAULT 'PENDING',
  settle_release_at timestamp(3) NULL,
  settle_at timestamp(3) NULL,
  settle_journal_no varchar(64) NULL,
  outbox_event_id varchar(64) NULL,
  extra_json json NULL,
  version integer NOT NULL DEFAULT 0,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payin_order PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payin_order_uk_pay_order_no ON payin_order (tenant_id, payin_order_no);
CREATE UNIQUE INDEX uk_payin_order_uk_pay_merchant_order ON payin_order (tenant_id, merchant_id, merchant_order_no);
CREATE UNIQUE INDEX uk_payin_order_uk_pay_idempotency ON payin_order (tenant_id, merchant_id, idempotency_key);
CREATE INDEX idx_payin_order_idx_pay_order_status ON payin_order (tenant_id, status, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_expire ON payin_order (tenant_id, status, expire_at);
CREATE INDEX idx_payin_order_idx_pay_order_settle ON payin_order (tenant_id, settle_status, paid_at);
CREATE INDEX idx_payin_order_idx_pay_order_merchant ON payin_order (tenant_id, merchant_id, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_psp ON payin_order (psp_id, psp_order_no);
CREATE INDEX idx_payin_order_idx_pay_order_psp_request ON payin_order (tenant_id, psp_request_no);
CREATE INDEX idx_payin_order_idx_pay_order_merchant_fee_rule ON payin_order (tenant_id, merchant_fee_rule_id, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_psp_fee_rule ON payin_order (tenant_id, psp_fee_rule_id, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_method ON payin_order (tenant_id, country_code, currency, method_code);
CREATE INDEX idx_payin_order_idx_pay_order_merchant_notify ON payin_order (tenant_id, merchant_notify_status, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_query ON payin_order (tenant_id, status, next_query_at);
CREATE INDEX idx_payin_order_idx_pay_order_settle_release ON payin_order (tenant_id, settle_status, settle_release_at);
CREATE INDEX idx_payin_order_idx_pay_order_submitted ON payin_order (tenant_id, status, submitted_at);
CREATE INDEX idx_payin_order_idx_pay_order_payment_plan ON payin_order (tenant_id, payment_plan_catalog_id, payment_plan_version, created_at);
CREATE INDEX idx_payin_order_idx_pay_order_route_source ON payin_order (tenant_id, route_group_id, route_channel_id, created_at);

DROP TABLE IF EXISTS payment_method CASCADE;
CREATE TABLE payment_method (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  method_code varchar(64) NOT NULL,
  method_name varchar(128) NOT NULL,
  method_type varchar(32) NULL,
  direction varchar(16) NULL,
  country_code varchar(8) NULL,
  currency varchar(16) NULL,
  status smallint NOT NULL DEFAULT 1,
  sort integer NOT NULL DEFAULT 100,
  icon_url varchar(512) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_method PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payment_method_uk_payment_method_scope ON payment_method (method_code, country_code, currency, direction);
CREATE INDEX idx_payment_method_idx_payment_method_query ON payment_method (country_code, currency, direction, status, sort);

DROP TABLE IF EXISTS payment_plan_bucket CASCADE;
CREATE TABLE payment_plan_bucket (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  catalog_id bigint NOT NULL,
  bucket_start_amount numeric(24, 8) NOT NULL,
  bucket_end_amount numeric(24, 8) NULL,
  merchant_fee_rule_id bigint NOT NULL,
  merchant_fee_snapshot_json json NULL,
  sort integer NOT NULL DEFAULT 0,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_plan_bucket PRIMARY KEY (id)
);
CREATE INDEX idx_payment_plan_bucket_idx_payment_plan_bucket_catalog ON payment_plan_bucket (tenant_id, catalog_id, sort);
CREATE INDEX idx_payment_plan_bucket_idx_payment_plan_bucket_amount ON payment_plan_bucket (tenant_id, catalog_id, bucket_start_amount, bucket_end_amount);

DROP TABLE IF EXISTS payment_plan_catalog CASCADE;
CREATE TABLE payment_plan_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_app_id bigint NOT NULL DEFAULT 0,
  direction varchar(32) NOT NULL,
  country_code varchar(32) NOT NULL DEFAULT '',
  currency varchar(16) NOT NULL,
  method_code varchar(64) NOT NULL,
  version bigint NOT NULL,
  status varchar(32) NOT NULL,
  bucket_count integer NOT NULL DEFAULT 0,
  route_option_count integer NOT NULL DEFAULT 0,
  config_hash varchar(128) NULL,
  compiled_at timestamp(3) NOT NULL,
  activated_at timestamp(3) NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_plan_catalog PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payment_plan_catalog_uk_payment_plan_catalog_version ON payment_plan_catalog (tenant_id, merchant_id, merchant_app_id, direction, country_code, currency, method_code, version);
CREATE INDEX idx_payment_plan_catalog_idx_payment_plan_catalog_active ON payment_plan_catalog (tenant_id, merchant_id, merchant_app_id, direction, country_code, currency, method_code, status);
CREATE INDEX idx_payment_plan_catalog_idx_payment_plan_catalog_created ON payment_plan_catalog (tenant_id, created_at);

DROP TABLE IF EXISTS payment_plan_route_option CASCADE;
CREATE TABLE payment_plan_route_option (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  catalog_id bigint NOT NULL,
  bucket_id bigint NOT NULL,
  route_rule_id bigint NOT NULL,
  route_group_id bigint NOT NULL,
  route_channel_id bigint NOT NULL,
  psp_id bigint NOT NULL,
  psp_code varchar(64) NULL,
  psp_method_id bigint NOT NULL,
  psp_method_code varchar(64) NULL,
  psp_account_id bigint NOT NULL,
  psp_account_no varchar(128) NULL,
  psp_fee_rule_id bigint NULL,
  psp_fee_snapshot_json json NULL,
  route_rule_snapshot_json json NULL,
  route_group_snapshot_json json NULL,
  route_channel_snapshot_json json NULL,
  psp_provider_snapshot_json json NULL,
  psp_method_snapshot_json json NULL,
  psp_account_snapshot_json json NULL,
  priority integer NOT NULL DEFAULT 100,
  weight integer NOT NULL DEFAULT 100,
  fallback_order integer NOT NULL DEFAULT 100,
  status varchar(32) NOT NULL DEFAULT 'ACTIVE',
  sort integer NOT NULL DEFAULT 0,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_plan_route_option PRIMARY KEY (id)
);
CREATE INDEX idx_payment_plan_route_option_idx_payment_plan_route_bucket ON payment_plan_route_option (tenant_id, bucket_id, status, priority, fallback_order);
CREATE INDEX idx_payment_plan_route_option_idx_payment_plan_route_catalog ON payment_plan_route_option (tenant_id, catalog_id, bucket_id, sort);
CREATE INDEX idx_payment_plan_route_option_idx_payment_plan_route_psp ON payment_plan_route_option (tenant_id, psp_id, psp_account_id);
CREATE INDEX idx_payment_plan_route_option_idx_payment_plan_route_source ON payment_plan_route_option (tenant_id, route_group_id, route_channel_id);

DROP TABLE IF EXISTS payment_route_channel CASCADE;
CREATE TABLE payment_route_channel (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  group_id bigint NOT NULL,
  psp_id bigint NOT NULL,
  psp_method_id bigint NOT NULL,
  psp_account_id bigint NOT NULL,
  psp_fee_rule_id bigint NULL,
  priority integer NOT NULL DEFAULT 100,
  weight integer NOT NULL DEFAULT 100,
  fallback_order integer NOT NULL DEFAULT 100,
  min_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_route_channel PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payment_route_channel_uk_payment_route_channel_resource ON payment_route_channel (tenant_id, group_id, psp_id, psp_method_id, psp_account_id);
CREATE INDEX idx_payment_route_channel_idx_payment_route_channel_group ON payment_route_channel (tenant_id, group_id, status, priority, fallback_order);
CREATE INDEX idx_payment_route_channel_idx_payment_route_channel_psp ON payment_route_channel (tenant_id, psp_id, psp_method_id, psp_account_id);
CREATE INDEX idx_payment_route_channel_idx_route_channel_psp_fee_rule ON payment_route_channel (psp_fee_rule_id);
CREATE INDEX idx_payment_route_channel_idx_payment_route_channel_fee_rule ON payment_route_channel (tenant_id, psp_fee_rule_id);

DROP TABLE IF EXISTS payment_route_group CASCADE;
CREATE TABLE payment_route_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  group_code varchar(64) NOT NULL,
  group_name varchar(128) NOT NULL,
  direction varchar(20) NOT NULL,
  country_code varchar(16) NOT NULL DEFAULT '',
  currency varchar(16) NOT NULL,
  method_code varchar(64) NOT NULL,
  strategy varchar(32) NOT NULL DEFAULT 'PRIORITY_WEIGHT',
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_route_group PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payment_route_group_uk_payment_route_group_code ON payment_route_group (tenant_id, group_code);
CREATE INDEX idx_payment_route_group_idx_payment_route_group_dimension ON payment_route_group (tenant_id, direction, country_code, currency, method_code, status);

DROP TABLE IF EXISTS payment_route_rule CASCADE;
CREATE TABLE payment_route_rule (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  rule_name varchar(128) NOT NULL,
  merchant_id bigint NULL,
  merchant_app_id bigint NULL,
  direction varchar(20) NOT NULL,
  country_code varchar(16) NOT NULL DEFAULT '',
  currency varchar(16) NOT NULL,
  method_code varchar(64) NOT NULL,
  min_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  max_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  group_id bigint NOT NULL,
  priority integer NOT NULL DEFAULT 100,
  effective_at timestamp(3) NULL,
  expire_at timestamp(3) NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payment_route_rule PRIMARY KEY (id)
);
CREATE INDEX idx_payment_route_rule_idx_payment_route_rule_match ON payment_route_rule (tenant_id, merchant_id, merchant_app_id, direction, country_code, currency, method_code, status, priority);
CREATE INDEX idx_payment_route_rule_idx_payment_route_rule_group ON payment_route_rule (tenant_id, group_id);
CREATE INDEX idx_payment_route_rule_idx_payment_route_rule_amount ON payment_route_rule (tenant_id, direction, currency, method_code, min_amount, max_amount);

DROP TABLE IF EXISTS payout_order CASCADE;
CREATE TABLE payout_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_no varchar(64) NOT NULL,
  merchant_app_id bigint NOT NULL,
  app_id varchar(64) NOT NULL,
  payout_order_no varchar(128) NOT NULL,
  merchant_order_no varchar(128) NOT NULL,
  idempotency_key varchar(128) NOT NULL,
  request_id varchar(128) NULL,
  order_source varchar(32) NOT NULL DEFAULT 'API',
  country_code varchar(8) NOT NULL,
  currency varchar(16) NOT NULL,
  method_code varchar(64) NOT NULL,
  amount numeric(24, 8) NOT NULL,
  merchant_fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  merchant_fee_rule_id bigint NULL,
  merchant_fee_snapshot_json json NULL,
  total_debit_amount numeric(24, 8) NOT NULL,
  psp_fee_amount numeric(24, 8) NOT NULL DEFAULT 0.00000000,
  psp_fee_rule_id bigint NULL,
  psp_fee_snapshot_json json NULL,
  payee_name varchar(128) NULL,
  payee_account_no varchar(256) NULL,
  payee_bank_code varchar(64) NULL,
  payee_wallet_type varchar(64) NULL,
  payee_phone varchar(64) NULL,
  payee_email varchar(128) NULL,
  payee_json json NULL,
  purpose varchar(256) NULL,
  notify_url varchar(512) NULL,
  merchant_notify_status varchar(16) NULL,
  merchant_notify_at timestamp(3) NULL,
  merchant_notify_task_id bigint NULL,
  status varchar(32) NOT NULL DEFAULT 'CREATED',
  status_reason varchar(512) NULL,
  merchant_status_code varchar(64) NULL,
  merchant_status_reason varchar(512) NULL,
  submitted_at timestamp(3) NULL,
  completed_at timestamp(3) NULL,
  failed_at timestamp(3) NULL,
  cancelled_at timestamp(3) NULL,
  fail_code varchar(128) NULL,
  fail_msg varchar(512) NULL,
  hold_no varchar(64) NULL,
  freeze_journal_no varchar(64) NULL,
  success_journal_no varchar(64) NULL,
  release_journal_no varchar(64) NULL,
  payment_plan_catalog_id bigint NULL,
  payment_plan_version bigint NULL,
  payment_plan_bucket_id bigint NULL,
  payment_plan_route_option_id bigint NULL,
  route_rule_id bigint NULL,
  route_group_id bigint NULL,
  route_channel_id bigint NULL,
  route_snapshot_json json NULL,
  psp_id bigint NULL,
  psp_code varchar(64) NULL,
  psp_method_id bigint NULL,
  psp_method_code varchar(128) NULL,
  psp_account_id bigint NULL,
  psp_account_no varchar(128) NULL,
  psp_request_no varchar(128) NULL,
  psp_order_no varchar(128) NULL,
  psp_status varchar(64) NULL,
  psp_raw_status varchar(128) NULL,
  next_query_at timestamp(3) NULL,
  query_count integer NOT NULL DEFAULT 0,
  outbox_event_id varchar(64) NULL,
  extra_json json NULL,
  version integer NOT NULL DEFAULT 0,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payout_order PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payout_order_uk_payout_order_no ON payout_order (tenant_id, payout_order_no);
CREATE UNIQUE INDEX uk_payout_order_uk_payout_merchant_order ON payout_order (tenant_id, merchant_id, merchant_order_no);
CREATE UNIQUE INDEX uk_payout_order_uk_payout_idempotency ON payout_order (tenant_id, merchant_id, idempotency_key);
CREATE INDEX idx_payout_order_idx_payout_order_status ON payout_order (tenant_id, status, created_at);
CREATE INDEX idx_payout_order_idx_payout_order_query ON payout_order (tenant_id, status, next_query_at);
CREATE INDEX idx_payout_order_idx_payout_order_merchant ON payout_order (tenant_id, merchant_id, created_at);
CREATE INDEX idx_payout_order_idx_payout_order_psp ON payout_order (psp_id, psp_order_no);
CREATE INDEX idx_payout_order_idx_payout_order_psp_request ON payout_order (tenant_id, psp_request_no);
CREATE INDEX idx_payout_order_idx_payout_order_merchant_fee_rule ON payout_order (tenant_id, merchant_fee_rule_id, created_at);
CREATE INDEX idx_payout_order_idx_payout_order_psp_fee_rule ON payout_order (tenant_id, psp_fee_rule_id, created_at);
CREATE INDEX idx_payout_order_idx_payout_order_hold ON payout_order (tenant_id, hold_no);
CREATE INDEX idx_payout_order_idx_payout_order_method ON payout_order (tenant_id, country_code, currency, method_code);
CREATE INDEX idx_payout_order_idx_payout_order_merchant_notify ON payout_order (tenant_id, merchant_notify_status, created_at);
CREATE INDEX idx_payout_order_idx_payout_payee_account_no ON payout_order (tenant_id, payee_account_no);
CREATE INDEX idx_payout_order_idx_payout_order_payment_plan ON payout_order (tenant_id, payment_plan_catalog_id, payment_plan_version, created_at);
CREATE INDEX idx_payout_order_idx_payout_order_route_source ON payout_order (tenant_id, route_group_id, route_channel_id, created_at);

DROP TABLE IF EXISTS payout_route_attempt CASCADE;
CREATE TABLE payout_route_attempt (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  payout_order_id bigint NOT NULL,
  payout_order_no varchar(128) NOT NULL,
  attempt_no integer NOT NULL,
  route_option_id bigint NULL,
  route_rule_id bigint NULL,
  route_group_id bigint NULL,
  route_channel_id bigint NULL,
  psp_id bigint NULL,
  psp_code varchar(64) NULL,
  psp_method_id bigint NULL,
  psp_method_code varchar(128) NULL,
  psp_account_id bigint NULL,
  psp_account_no varchar(128) NULL,
  psp_bank_code varchar(128) NULL,
  submit_result_status varchar(32) NULL,
  error_code varchar(128) NULL,
  error_message varchar(512) NULL,
  psp_request_no varchar(128) NULL,
  psp_order_no varchar(128) NULL,
  raw_status varchar(128) NULL,
  response_status integer NULL,
  response_code varchar(128) NULL,
  response_message varchar(512) NULL,
  raw_response_json json NULL,
  remark varchar(512) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_payout_route_attempt PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_payout_route_attempt_uk_payout_route_attempt_no ON payout_route_attempt (tenant_id, payout_order_id, attempt_no);
CREATE INDEX idx_payout_route_attempt_idx_payout_route_attempt_order ON payout_route_attempt (tenant_id, payout_order_no, attempt_no);
CREATE INDEX idx_payout_route_attempt_idx_payout_route_attempt_psp ON payout_route_attempt (tenant_id, psp_id, psp_account_id, created_at);
CREATE INDEX idx_payout_route_attempt_idx_payout_route_attempt_bank ON payout_route_attempt (tenant_id, psp_bank_code, created_at);
CREATE INDEX idx_payout_route_attempt_idx_payout_route_attempt_result ON payout_route_attempt (tenant_id, submit_result_status, created_at);
CREATE INDEX idx_payout_route_attempt_idx_payout_route_attempt_request ON payout_route_attempt (tenant_id, psp_request_no);

DROP TABLE IF EXISTS sys_tenant_currency CASCADE;
CREATE TABLE sys_tenant_currency (
  id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  currency varchar(8) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  sort integer NOT NULL DEFAULT 100,
  remark varchar(500) NULL,
  created_by bigint NULL,
  created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by bigint NULL,
  updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_sys_tenant_currency PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_sys_tenant_currency_uk_tenant_currency ON sys_tenant_currency (tenant_id, currency);
CREATE INDEX idx_sys_tenant_currency_idx_tenant_status ON sys_tenant_currency (tenant_id, status);
CREATE INDEX idx_sys_tenant_currency_idx_currency ON sys_tenant_currency (currency);
