/*
 Navicat Premium Dump SQL

 Source Server         : 涓汉鏁版嵁搴?HK)
 Source Server Type    : MySQL
 Source Server Version : 80036 (8.0.36)
 Source Host           : rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306
 Source Schema         : gk-union

 Target Server Type    : MySQL
 Target Server Version : 80036 (8.0.36)
 File Encoding         : 65001

 Date: 10/06/2026 12:31:23
*/



-- ----------------------------
-- Table structure for payin_order
-- ----------------------------
DROP TABLE IF EXISTS "payin_order";
CREATE TABLE "payin_order"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "merchant_no" varchar(64) NOT NULL,
  "merchant_app_id" bigint NOT NULL,
  "app_id" varchar(64) NOT NULL,
  "payin_order_no" varchar(128) NOT NULL,
  "merchant_order_no" varchar(128) NOT NULL,
  "idempotency_key" varchar(128) NOT NULL,
  "request_id" varchar(128) NULL DEFAULT NULL,
  "order_source" varchar(32) NOT NULL DEFAULT 'API',
  "country_code" varchar(8) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "amount" decimal(24, 8) NOT NULL,
  "paid_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "merchant_fee_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "merchant_fee_rule_id" bigint NULL DEFAULT NULL,
  "merchant_fee_snapshot_json" json NULL,
  "psp_fee_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "psp_fee_rule_id" bigint NULL DEFAULT NULL,
  "psp_fee_snapshot_json" json NULL,
  "settle_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "subject" varchar(256) NULL DEFAULT NULL,
  "description" varchar(512) NULL DEFAULT NULL,
  "client_ip" varchar(64) NULL DEFAULT NULL,
  "payer_json" json NULL,
  "notify_url" varchar(512) NULL DEFAULT NULL,
  "return_url" varchar(512) NULL DEFAULT NULL,
  "merchant_notify_status" varchar(16) NULL DEFAULT NULL,
  "merchant_notify_at" TIMESTAMP NULL DEFAULT NULL,
  "merchant_notify_task_id" bigint NULL DEFAULT NULL,
  "status" varchar(32) NOT NULL DEFAULT 'CREATED',
  "status_reason" varchar(512) NULL DEFAULT NULL,
  "merchant_status_code" varchar(64) NULL DEFAULT NULL,
  "merchant_status_reason" varchar(512) NULL DEFAULT NULL,
  "expire_at" TIMESTAMP NULL DEFAULT NULL,
  "paid_at" TIMESTAMP NULL DEFAULT NULL,
  "closed_at" TIMESTAMP NULL DEFAULT NULL,
  "failed_at" TIMESTAMP NULL DEFAULT NULL,
  "payment_plan_catalog_id" bigint NULL DEFAULT NULL,
  "payment_plan_version" bigint NULL DEFAULT NULL,
  "payment_plan_bucket_id" bigint NULL DEFAULT NULL,
  "payment_plan_route_option_id" bigint NULL DEFAULT NULL,
  "route_rule_id" bigint NULL DEFAULT NULL,
  "route_group_id" bigint NULL DEFAULT NULL,
  "route_channel_id" bigint NULL DEFAULT NULL,
  "route_snapshot_json" json NULL,
  "psp_id" bigint NULL DEFAULT NULL,
  "psp_code" varchar(64) NULL DEFAULT NULL,
  "psp_method_id" bigint NULL DEFAULT NULL,
  "psp_method_code" varchar(128) NULL DEFAULT NULL,
  "psp_account_id" bigint NULL DEFAULT NULL,
  "psp_account_no" varchar(128) NULL DEFAULT NULL,
  "psp_request_no" varchar(128) NULL DEFAULT NULL,
  "psp_order_no" varchar(128) NULL DEFAULT NULL,
  "psp_status" varchar(64) NULL DEFAULT NULL,
  "psp_raw_status" varchar(128) NULL DEFAULT NULL,
  "psp_pay_url" varchar(1024) NULL DEFAULT NULL,
  "psp_pay_params_json" json NULL,
  "next_query_at" TIMESTAMP NULL DEFAULT NULL,
  "query_count" int NOT NULL DEFAULT 0,
  "submitted_at" TIMESTAMP NULL DEFAULT NULL,
  "ledger_journal_no" varchar(64) NULL DEFAULT NULL,
  "settle_status" varchar(32) NOT NULL DEFAULT 'PENDING',
  "settle_release_at" TIMESTAMP NULL DEFAULT NULL,
  "settle_at" TIMESTAMP NULL DEFAULT NULL,
  "settle_journal_no" varchar(64) NULL DEFAULT NULL,
  "outbox_event_id" varchar(64) NULL DEFAULT NULL,
  "extra_json" json NULL,
  "version" int NOT NULL DEFAULT 0,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payin_order_no" ON "payin_order" ("tenant_id" ASC, "payin_order_no" ASC);
CREATE UNIQUE INDEX "uk_pay_merchant_order" ON "payin_order" ("tenant_id" ASC, "merchant_id" ASC, "merchant_order_no" ASC);
CREATE UNIQUE INDEX "uk_pay_idempotency" ON "payin_order" ("tenant_id" ASC, "merchant_id" ASC, "idempotency_key" ASC);
CREATE INDEX "idx_payin_order_status" ON "payin_order" ("tenant_id" ASC, "status" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_query" ON "payin_order" ("tenant_id" ASC, "status" ASC, "next_query_at" ASC);
CREATE INDEX "idx_payin_order_expire" ON "payin_order" ("tenant_id" ASC, "status" ASC, "expire_at" ASC);
CREATE INDEX "idx_payin_order_settle" ON "payin_order" ("tenant_id" ASC, "settle_status" ASC, "paid_at" ASC);
CREATE INDEX "idx_payin_order_settle_release" ON "payin_order" ("tenant_id" ASC, "settle_status" ASC, "settle_release_at" ASC);
CREATE INDEX "idx_payin_order_merchant" ON "payin_order" ("tenant_id" ASC, "merchant_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_psp" ON "payin_order" ("psp_id" ASC, "psp_order_no" ASC);
CREATE INDEX "idx_payin_order_payment_plan" ON "payin_order" ("tenant_id" ASC, "payment_plan_catalog_id" ASC, "payment_plan_version" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_route_source" ON "payin_order" ("tenant_id" ASC, "route_group_id" ASC, "route_channel_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_psp_request" ON "payin_order" ("tenant_id" ASC, "psp_request_no" ASC);
CREATE INDEX "idx_payin_order_merchant_fee_rule" ON "payin_order" ("tenant_id" ASC, "merchant_fee_rule_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_psp_fee_rule" ON "payin_order" ("tenant_id" ASC, "psp_fee_rule_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payin_order_method" ON "payin_order" ("tenant_id" ASC, "country_code" ASC, "currency" ASC, "method_code" ASC);
CREATE INDEX "idx_payin_order_merchant_notify" ON "payin_order" ("tenant_id" ASC, "merchant_notify_status" ASC, "created_at" ASC);

-- ----------------------------
-- Table structure for payout_order
-- ----------------------------
DROP TABLE IF EXISTS "payout_order";
CREATE TABLE "payout_order"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "merchant_no" varchar(64) NOT NULL,
  "merchant_app_id" bigint NOT NULL,
  "app_id" varchar(64) NOT NULL,
  "payout_order_no" varchar(128) NOT NULL,
  "merchant_order_no" varchar(128) NOT NULL,
  "idempotency_key" varchar(128) NOT NULL,
  "request_id" varchar(128) NULL DEFAULT NULL,
  "order_source" varchar(32) NOT NULL DEFAULT 'API',
  "country_code" varchar(8) NOT NULL,
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "amount" decimal(24, 8) NOT NULL,
  "merchant_fee_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "merchant_fee_rule_id" bigint NULL DEFAULT NULL,
  "merchant_fee_snapshot_json" json NULL,
  "total_debit_amount" decimal(24, 8) NOT NULL,
  "psp_fee_amount" decimal(24, 8) NOT NULL DEFAULT 0.00000000,
  "psp_fee_rule_id" bigint NULL DEFAULT NULL,
  "psp_fee_snapshot_json" json NULL,
  "payee_name" varchar(128) NULL DEFAULT NULL,
  "payee_account_no" varchar(256) NULL DEFAULT NULL,
  "payee_bank_code" varchar(64) NULL DEFAULT NULL,
  "payee_wallet_type" varchar(64) NULL DEFAULT NULL,
  "payee_phone" varchar(64) NULL DEFAULT NULL,
  "payee_email" varchar(128) NULL DEFAULT NULL,
  "payee_json" json NULL,
  "purpose" varchar(256) NULL DEFAULT NULL,
  "notify_url" varchar(512) NULL DEFAULT NULL,
  "merchant_notify_status" varchar(16) NULL DEFAULT NULL,
  "merchant_notify_at" TIMESTAMP NULL DEFAULT NULL,
  "merchant_notify_task_id" bigint NULL DEFAULT NULL,
  "status" varchar(32) NOT NULL DEFAULT 'CREATED',
  "status_reason" varchar(512) NULL DEFAULT NULL,
  "merchant_status_code" varchar(64) NULL DEFAULT NULL,
  "merchant_status_reason" varchar(512) NULL DEFAULT NULL,
  "submitted_at" TIMESTAMP NULL DEFAULT NULL,
  "completed_at" TIMESTAMP NULL DEFAULT NULL,
  "failed_at" TIMESTAMP NULL DEFAULT NULL,
  "cancelled_at" TIMESTAMP NULL DEFAULT NULL,
  "fail_code" varchar(128) NULL DEFAULT NULL,
  "fail_msg" varchar(512) NULL DEFAULT NULL,
  "hold_no" varchar(64) NULL DEFAULT NULL,
  "freeze_journal_no" varchar(64) NULL DEFAULT NULL,
  "success_journal_no" varchar(64) NULL DEFAULT NULL,
  "release_journal_no" varchar(64) NULL DEFAULT NULL,
  "payment_plan_catalog_id" bigint NULL DEFAULT NULL,
  "payment_plan_version" bigint NULL DEFAULT NULL,
  "payment_plan_bucket_id" bigint NULL DEFAULT NULL,
  "payment_plan_route_option_id" bigint NULL DEFAULT NULL,
  "route_rule_id" bigint NULL DEFAULT NULL,
  "route_group_id" bigint NULL DEFAULT NULL,
  "route_channel_id" bigint NULL DEFAULT NULL,
  "route_snapshot_json" json NULL,
  "psp_id" bigint NULL DEFAULT NULL,
  "psp_code" varchar(64) NULL DEFAULT NULL,
  "psp_method_id" bigint NULL DEFAULT NULL,
  "psp_method_code" varchar(128) NULL DEFAULT NULL,
  "psp_account_id" bigint NULL DEFAULT NULL,
  "psp_account_no" varchar(128) NULL DEFAULT NULL,
  "psp_request_no" varchar(128) NULL DEFAULT NULL,
  "psp_order_no" varchar(128) NULL DEFAULT NULL,
  "psp_status" varchar(64) NULL DEFAULT NULL,
  "psp_raw_status" varchar(128) NULL DEFAULT NULL,
  "next_query_at" TIMESTAMP NULL DEFAULT NULL,
  "query_count" int NOT NULL DEFAULT 0,
  "outbox_event_id" varchar(64) NULL DEFAULT NULL,
  "extra_json" json NULL,
  "version" int NOT NULL DEFAULT 0,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payout_order_no" ON "payout_order" ("tenant_id" ASC, "payout_order_no" ASC);
CREATE UNIQUE INDEX "uk_payout_merchant_order" ON "payout_order" ("tenant_id" ASC, "merchant_id" ASC, "merchant_order_no" ASC);
CREATE UNIQUE INDEX "uk_payout_idempotency" ON "payout_order" ("tenant_id" ASC, "merchant_id" ASC, "idempotency_key" ASC);
CREATE INDEX "idx_payout_order_status" ON "payout_order" ("tenant_id" ASC, "status" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_query" ON "payout_order" ("tenant_id" ASC, "status" ASC, "next_query_at" ASC);
CREATE INDEX "idx_payout_order_merchant" ON "payout_order" ("tenant_id" ASC, "merchant_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_psp" ON "payout_order" ("psp_id" ASC, "psp_order_no" ASC);
CREATE INDEX "idx_payout_order_payment_plan" ON "payout_order" ("tenant_id" ASC, "payment_plan_catalog_id" ASC, "payment_plan_version" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_route_source" ON "payout_order" ("tenant_id" ASC, "route_group_id" ASC, "route_channel_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_psp_request" ON "payout_order" ("tenant_id" ASC, "psp_request_no" ASC);
CREATE INDEX "idx_payout_order_merchant_fee_rule" ON "payout_order" ("tenant_id" ASC, "merchant_fee_rule_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_psp_fee_rule" ON "payout_order" ("tenant_id" ASC, "psp_fee_rule_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_order_hold" ON "payout_order" ("tenant_id" ASC, "hold_no" ASC);
CREATE INDEX "idx_payout_payee_account_no" ON "payout_order" ("tenant_id" ASC, "payee_account_no" ASC);
CREATE INDEX "idx_payout_order_method" ON "payout_order" ("tenant_id" ASC, "country_code" ASC, "currency" ASC, "method_code" ASC);
CREATE INDEX "idx_payout_order_merchant_notify" ON "payout_order" ("tenant_id" ASC, "merchant_notify_status" ASC, "created_at" ASC);


-- ----------------------------
-- Table structure for payout_route_attempt
-- ----------------------------

DROP TABLE IF EXISTS "payout_route_attempt";
CREATE TABLE "payout_route_attempt"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "payout_order_id" bigint NOT NULL,
  "payout_order_no" varchar(128) NOT NULL,
  "attempt_no" int NOT NULL,
  "route_option_id" bigint NULL DEFAULT NULL,
  "route_rule_id" bigint NULL DEFAULT NULL,
  "route_group_id" bigint NULL DEFAULT NULL,
  "route_channel_id" bigint NULL DEFAULT NULL,
  "psp_id" bigint NULL DEFAULT NULL,
  "psp_code" varchar(64) NULL DEFAULT NULL,
  "psp_method_id" bigint NULL DEFAULT NULL,
  "psp_method_code" varchar(128) NULL DEFAULT NULL,
  "psp_account_id" bigint NULL DEFAULT NULL,
  "psp_account_no" varchar(128) NULL DEFAULT NULL,
  "psp_bank_code" varchar(128) NULL DEFAULT NULL,
  "submit_result_status" varchar(32) NULL DEFAULT NULL,
  "error_code" varchar(128) NULL DEFAULT NULL,
  "error_message" varchar(512) NULL DEFAULT NULL,
  "psp_request_no" varchar(128) NULL DEFAULT NULL,
  "psp_order_no" varchar(128) NULL DEFAULT NULL,
  "raw_status" varchar(128) NULL DEFAULT NULL,
  "response_status" int NULL DEFAULT NULL,
  "response_code" varchar(128) NULL DEFAULT NULL,
  "response_message" varchar(512) NULL DEFAULT NULL,
  "raw_response_json" json NULL,
  "remark" varchar(512) NULL DEFAULT NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payout_route_attempt_no" ON "payout_route_attempt" ("tenant_id" ASC, "payout_order_id" ASC, "attempt_no" ASC);
CREATE INDEX "idx_payout_route_attempt_order" ON "payout_route_attempt" ("tenant_id" ASC, "payout_order_no" ASC, "attempt_no" ASC);
CREATE INDEX "idx_payout_route_attempt_psp" ON "payout_route_attempt" ("tenant_id" ASC, "psp_id" ASC, "psp_account_id" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_route_attempt_bank" ON "payout_route_attempt" ("tenant_id" ASC, "psp_bank_code" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_route_attempt_result" ON "payout_route_attempt" ("tenant_id" ASC, "submit_result_status" ASC, "created_at" ASC);
CREATE INDEX "idx_payout_route_attempt_request" ON "payout_route_attempt" ("tenant_id" ASC, "psp_request_no" ASC);
-- ----------------------------
-- Table structure for order_status_log
-- ----------------------------
DROP TABLE IF EXISTS "order_status_log";
CREATE TABLE "order_status_log"  (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NULL DEFAULT NULL,
  "log_no" varchar(128) NOT NULL,
  "direction" varchar(32) NOT NULL,
  "order_id" bigint NOT NULL,
  "order_no" varchar(128) NOT NULL,
  "from_status" varchar(32) NULL DEFAULT NULL,
  "to_status" varchar(32) NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "reason" varchar(512) NULL DEFAULT NULL,
  "operator_type" varchar(32) NOT NULL DEFAULT 'SYSTEM',
  "operator_id" varchar(128) NULL DEFAULT NULL,
  "request_id" varchar(128) NULL DEFAULT NULL,
  "trace_id" varchar(128) NULL DEFAULT NULL,
  "metadata_json" json NULL,
  "created_by" bigint NULL DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint NULL DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_order_status_log_no" ON "order_status_log" ("tenant_id" ASC, "log_no" ASC);
CREATE INDEX "idx_order_status_order" ON "order_status_log" ("tenant_id" ASC, "direction" ASC, "order_no" ASC, "created_at" ASC);
CREATE INDEX "idx_order_status_event" ON "order_status_log" ("tenant_id" ASC, "event_type" ASC, "created_at" ASC);
