-- 鏀粯璺敱涓庢敮浠樻柟妗堟寮忕粨鏋勩€?
-- 鏂伴」鐩笂绾夸娇鐢ㄦ湰鏂囦欢锛屼笉鍐嶄娇鐢ㄦ棫鐨?PSP 鐩磋繛璺敱琛ㄣ€?

DROP TABLE IF EXISTS "payment_plan_route_option";
DROP TABLE IF EXISTS "payment_plan_bucket";
DROP TABLE IF EXISTS "payment_plan_catalog";
DROP TABLE IF EXISTS "payment_route_rule";
DROP TABLE IF EXISTS "payment_route_channel";
DROP TABLE IF EXISTS "payment_route_group";

CREATE TABLE "payment_route_group" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "group_code" varchar(64) NOT NULL,
  "group_name" varchar(128) NOT NULL,
  "direction" varchar(20) NOT NULL,
  "country_code" varchar(16) NOT NULL DEFAULT '',
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "strategy" varchar(32) NOT NULL DEFAULT 'PRIORITY_WEIGHT',
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) DEFAULT NULL,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payment_route_group_code" ON "payment_route_group" ("tenant_id", "group_code");
CREATE INDEX "idx_payment_route_group_dimension" ON "payment_route_group" ("tenant_id", "direction", "country_code", "currency", "method_code", "status");

CREATE TABLE "payment_route_channel" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "group_id" bigint NOT NULL,
  "psp_id" bigint NOT NULL,
  "psp_method_id" bigint NOT NULL,
  "psp_account_id" bigint NOT NULL,
  "psp_fee_rule_id" bigint DEFAULT NULL,
  "priority" int NOT NULL DEFAULT 100,
  "weight" int NOT NULL DEFAULT 100,
  "fallback_order" int NOT NULL DEFAULT 100,
  "min_amount" decimal(24,8) NOT NULL DEFAULT '0.00000000',
  "max_amount" decimal(24,8) NOT NULL DEFAULT '0.00000000',
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) DEFAULT NULL,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payment_route_channel_resource" ON "payment_route_channel" ("tenant_id", "group_id", "psp_id", "psp_method_id", "psp_account_id");
CREATE INDEX "idx_payment_route_channel_group" ON "payment_route_channel" ("tenant_id", "group_id", "status", "priority", "fallback_order");
CREATE INDEX "idx_payment_route_channel_psp" ON "payment_route_channel" ("tenant_id", "psp_id", "psp_method_id", "psp_account_id");
CREATE INDEX "idx_payment_route_channel_fee_rule" ON "payment_route_channel" ("tenant_id", "psp_fee_rule_id");

CREATE TABLE "payment_route_rule" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "rule_name" varchar(128) NOT NULL,
  "merchant_id" bigint DEFAULT NULL,
  "merchant_app_id" bigint DEFAULT NULL,
  "direction" varchar(20) NOT NULL,
  "country_code" varchar(16) NOT NULL DEFAULT '',
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "min_amount" decimal(24,8) NOT NULL DEFAULT '0.00000000',
  "max_amount" decimal(24,8) NOT NULL DEFAULT '0.00000000',
  "group_id" bigint NOT NULL,
  "priority" int NOT NULL DEFAULT 100,
  "effective_at" TIMESTAMP DEFAULT NULL,
  "expire_at" TIMESTAMP DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "remark" varchar(512) DEFAULT NULL,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE INDEX "idx_payment_route_rule_match" ON "payment_route_rule" ("tenant_id", "merchant_id", "merchant_app_id", "direction", "country_code", "currency", "method_code", "status", "priority");
CREATE INDEX "idx_payment_route_rule_group" ON "payment_route_rule" ("tenant_id", "group_id");
CREATE INDEX "idx_payment_route_rule_amount" ON "payment_route_rule" ("tenant_id", "direction", "currency", "method_code", "min_amount", "max_amount");

CREATE TABLE "payment_plan_catalog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "merchant_id" bigint NOT NULL,
  "merchant_app_id" bigint NOT NULL DEFAULT 0,
  "direction" varchar(32) NOT NULL,
  "country_code" varchar(32) NOT NULL DEFAULT '',
  "currency" varchar(16) NOT NULL,
  "method_code" varchar(64) NOT NULL,
  "version" bigint NOT NULL,
  "status" varchar(32) NOT NULL,
  "bucket_count" int NOT NULL DEFAULT 0,
  "route_option_count" int NOT NULL DEFAULT 0,
  "config_hash" varchar(128) DEFAULT NULL,
  "compiled_at" TIMESTAMP NOT NULL,
  "activated_at" TIMESTAMP DEFAULT NULL,
  "remark" varchar(512) DEFAULT NULL,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  "updated_by" bigint DEFAULT NULL,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE UNIQUE INDEX "uk_payment_plan_catalog_version" ON "payment_plan_catalog" ("tenant_id", "merchant_id", "merchant_app_id", "direction", "country_code", "currency", "method_code", "version");
CREATE INDEX "idx_payment_plan_catalog_active" ON "payment_plan_catalog" ("tenant_id", "merchant_id", "merchant_app_id", "direction", "country_code", "currency", "method_code", "status");
CREATE INDEX "idx_payment_plan_catalog_created" ON "payment_plan_catalog" ("tenant_id", "created_at");

CREATE TABLE "payment_plan_bucket" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "catalog_id" bigint NOT NULL,
  "bucket_start_amount" decimal(24,8) NOT NULL,
  "bucket_end_amount" decimal(24,8) DEFAULT NULL,
  "merchant_fee_rule_id" bigint NOT NULL,
  "merchant_fee_snapshot_json" json DEFAULT NULL,
  "sort" int NOT NULL DEFAULT 0,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE INDEX "idx_payment_plan_bucket_catalog" ON "payment_plan_bucket" ("tenant_id", "catalog_id", "sort");
CREATE INDEX "idx_payment_plan_bucket_amount" ON "payment_plan_bucket" ("tenant_id", "catalog_id", "bucket_start_amount", "bucket_end_amount");

CREATE TABLE "payment_plan_route_option" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "catalog_id" bigint NOT NULL,
  "bucket_id" bigint NOT NULL,
  "route_rule_id" bigint NOT NULL,
  "route_group_id" bigint NOT NULL,
  "route_channel_id" bigint NOT NULL,
  "psp_id" bigint NOT NULL,
  "psp_code" varchar(64) DEFAULT NULL,
  "psp_method_id" bigint NOT NULL,
  "psp_method_code" varchar(64) DEFAULT NULL,
  "psp_account_id" bigint NOT NULL,
  "psp_account_no" varchar(128) DEFAULT NULL,
  "psp_fee_rule_id" bigint DEFAULT NULL,
  "psp_fee_snapshot_json" json DEFAULT NULL,
  "route_rule_snapshot_json" json DEFAULT NULL,
  "route_group_snapshot_json" json DEFAULT NULL,
  "route_channel_snapshot_json" json DEFAULT NULL,
  "psp_provider_snapshot_json" json DEFAULT NULL,
  "psp_method_snapshot_json" json DEFAULT NULL,
  "psp_account_snapshot_json" json DEFAULT NULL,
  "priority" int NOT NULL DEFAULT 100,
  "weight" int NOT NULL DEFAULT 100,
  "fallback_order" int NOT NULL DEFAULT 100,
  "status" varchar(32) NOT NULL DEFAULT 'ACTIVE',
  "sort" int NOT NULL DEFAULT 0,
  "created_by" bigint DEFAULT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY ("id"),
);
CREATE INDEX "idx_payment_plan_route_bucket" ON "payment_plan_route_option" ("tenant_id", "bucket_id", "status", "priority", "fallback_order");
CREATE INDEX "idx_payment_plan_route_catalog" ON "payment_plan_route_option" ("tenant_id", "catalog_id", "bucket_id", "sort");
CREATE INDEX "idx_payment_plan_route_psp" ON "payment_plan_route_option" ("tenant_id", "psp_id", "psp_account_id");
CREATE INDEX "idx_payment_plan_route_source" ON "payment_plan_route_option" ("tenant_id", "route_group_id", "route_channel_id");
