<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gk</groupId>
        <artifactId>gk-union</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>gk-openapi</artifactId>
    <name>gk-openapi</name>
    <description>Merchant OpenAPI, request signing, request DTO and entrance error handling module</description>

    <dependencies>
        <dependency>
            <groupId>com.gk</groupId>
            <artifactId>gk-payment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gk</groupId>
            <artifactId>gk-ledger</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gk</groupId>
            <artifactId>gk-merchant</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gk</groupId>
            <artifactId>gk-psp</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
