package com.gk.payment.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.gk.common.core.entity.SimpleEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.Instant;

/**
 * Payment plan catalog generated by admin publish.
 * <p>
 * Merchant API only reads ACTIVE catalogs at runtime.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("payment_plan_catalog")
public class PaymentPlanCatalogEntity extends SimpleEntity {
    private Long tenantId;
    private Long merchantId;
    private Long merchantAppId;
    private String direction;
    private String countryCode;
    private String currency;
    private String methodCode;
    private Long version;
    private String status;
    private Integer bucketCount;
    private Integer routeOptionCount;
    private String configHash;
    private Instant compiledAt;
    private Instant activatedAt;
    private String remark;
}
